import type { RoleDefinitionSeed } from '../types';

/** Default system roles matching legacy hardcoded behavior. */
export const DEFAULT_ROLE_DEFINITIONS: RoleDefinitionSeed[] = [
  {
    key: 'owner',
    label: 'Owner',
    rank: 0,
    isSystem: true,
    active: true,
    canEditMaster: true,
    canManageUsers: true,
    canReview: true,
    canPreApproveAccess: false,
    canAccessAllStores: true,
    seesAllTemplateItems: true,
    canExportDashboard: true,
    canExportReviewStatus: false,
    canScheduleShifts: true,
    canDeleteShifts: true,
    canUseOpsTools: true,
    canClockIn: true,
    canProposeTemplateItem: false,
    canFirstApproveTemplateItemProposal: true,
    canFinalApproveTemplateItemProposal: true,
    canPublishTemplateItemProposal: true,
    approvesSubmitterRolesJson: '[]',
  },
  {
    key: 'admin',
    label: 'Admin',
    rank: 1,
    isSystem: true,
    active: true,
    canEditMaster: true,
    canManageUsers: true,
    canReview: true,
    canPreApproveAccess: false,
    canAccessAllStores: true,
    seesAllTemplateItems: true,
    canExportDashboard: true,
    canExportReviewStatus: false,
    canScheduleShifts: true,
    canDeleteShifts: true,
    canUseOpsTools: true,
    canClockIn: true,
    canProposeTemplateItem: false,
    canFirstApproveTemplateItemProposal: true,
    canFinalApproveTemplateItemProposal: true,
    canPublishTemplateItemProposal: true,
    approvesSubmitterRolesJson: '["leader","subleader","manager"]',
  },
  {
    key: 'areaManager',
    label: 'Area manager',
    rank: 2,
    isSystem: true,
    active: true,
    canEditMaster: true,
    canManageUsers: true,
    canReview: true,
    canPreApproveAccess: false,
    canAccessAllStores: true,
    seesAllTemplateItems: true,
    canExportDashboard: true,
    canExportReviewStatus: false,
    canScheduleShifts: true,
    canDeleteShifts: true,
    canUseOpsTools: true,
    canClockIn: true,
    canProposeTemplateItem: false,
    canFirstApproveTemplateItemProposal: true,
    canFinalApproveTemplateItemProposal: true,
    canPublishTemplateItemProposal: true,
    approvesSubmitterRolesJson: '["leader","subleader","manager"]',
  },
  {
    key: 'manager',
    label: 'Manager',
    rank: 3,
    isSystem: true,
    active: true,
    canEditMaster: false,
    canManageUsers: false,
    canReview: true,
    canPreApproveAccess: true,
    canAccessAllStores: false,
    seesAllTemplateItems: false,
    canExportDashboard: false,
    canExportReviewStatus: true,
    canScheduleShifts: true,
    canDeleteShifts: false,
    canUseOpsTools: true,
    canClockIn: true,
    canProposeTemplateItem: true,
    canFirstApproveTemplateItemProposal: true,
    canFinalApproveTemplateItemProposal: false,
    canPublishTemplateItemProposal: false,
    approvesSubmitterRolesJson: '["staff","hybrid"]',
  },
  {
    key: 'leader',
    label: 'Leader',
    rank: 4,
    isSystem: true,
    active: true,
    canEditMaster: false,
    canManageUsers: false,
    canReview: true,
    canPreApproveAccess: false,
    canAccessAllStores: false,
    seesAllTemplateItems: false,
    canExportDashboard: false,
    canExportReviewStatus: true,
    canScheduleShifts: false,
    canDeleteShifts: false,
    canUseOpsTools: true,
    canClockIn: true,
    canProposeTemplateItem: true,
    canFirstApproveTemplateItemProposal: false,
    canFinalApproveTemplateItemProposal: false,
    canPublishTemplateItemProposal: false,
    approvesSubmitterRolesJson: '["staff","hybrid"]',
  },
  {
    key: 'subleader',
    label: 'Subleader',
    rank: 5,
    isSystem: true,
    active: true,
    canEditMaster: false,
    canManageUsers: false,
    canReview: true,
    canPreApproveAccess: false,
    canAccessAllStores: false,
    seesAllTemplateItems: false,
    canExportDashboard: false,
    canExportReviewStatus: true,
    canScheduleShifts: false,
    canDeleteShifts: false,
    canUseOpsTools: true,
    canClockIn: true,
    canProposeTemplateItem: true,
    canFirstApproveTemplateItemProposal: false,
    canFinalApproveTemplateItemProposal: false,
    canPublishTemplateItemProposal: false,
    approvesSubmitterRolesJson: '["staff","hybrid"]',
  },
  {
    key: 'hybrid',
    label: 'Hybrid',
    rank: 6,
    isSystem: true,
    active: true,
    canEditMaster: false,
    canManageUsers: false,
    canReview: true,
    canPreApproveAccess: false,
    canAccessAllStores: false,
    seesAllTemplateItems: false,
    canExportDashboard: false,
    canExportReviewStatus: true,
    canScheduleShifts: false,
    canDeleteShifts: false,
    canUseOpsTools: false,
    canClockIn: true,
    canProposeTemplateItem: false,
    canFirstApproveTemplateItemProposal: false,
    canFinalApproveTemplateItemProposal: false,
    canPublishTemplateItemProposal: false,
    approvesSubmitterRolesJson: '["staff"]',
  },
  {
    key: 'staff',
    label: 'Staff',
    rank: 7,
    isSystem: true,
    active: true,
    canEditMaster: false,
    canManageUsers: false,
    canReview: false,
    canPreApproveAccess: false,
    canAccessAllStores: false,
    seesAllTemplateItems: false,
    canExportDashboard: false,
    canExportReviewStatus: false,
    canScheduleShifts: false,
    canDeleteShifts: false,
    canUseOpsTools: false,
    canClockIn: true,
    canProposeTemplateItem: false,
    canFirstApproveTemplateItemProposal: false,
    canFinalApproveTemplateItemProposal: false,
    canPublishTemplateItemProposal: false,
    approvesSubmitterRolesJson: '[]',
  },
  {
    key: 'viewer',
    label: 'Viewer',
    rank: 8,
    isSystem: true,
    active: true,
    canEditMaster: false,
    canManageUsers: false,
    canReview: false,
    canPreApproveAccess: false,
    canAccessAllStores: false,
    seesAllTemplateItems: false,
    canExportDashboard: false,
    canExportReviewStatus: false,
    canScheduleShifts: false,
    canDeleteShifts: false,
    canUseOpsTools: false,
    canClockIn: false,
    canProposeTemplateItem: false,
    canFirstApproveTemplateItemProposal: false,
    canFinalApproveTemplateItemProposal: false,
    canPublishTemplateItemProposal: false,
    approvesSubmitterRolesJson: '[]',
  },
];

export const SYSTEM_ROLE_KEYS = DEFAULT_ROLE_DEFINITIONS.map((d) => d.key);

export const LEGACY_ROLES = SYSTEM_ROLE_KEYS;
