/* Generated by scripts/bundle-export-api.mjs — do not edit by hand */

// api/_lib/export/routes.js
import { id as id2 } from "@instantdb/admin";

// api/_lib/export/instant-admin.js
import { init } from "@instantdb/admin";
var DEFAULT_APP_ID = "f7ac027e-2079-41eb-8f34-aa0e4543ca71";
function getCredentials() {
  const appId = process.env.VITE_INSTANT_APP_ID || process.env.INSTANT_APP_ID || DEFAULT_APP_ID;
  const adminToken = process.env.INSTANT_ADMIN_TOKEN || process.env.INSTANT_APP_ADMIN_TOKEN || process.env.INSTANT_CLI_AUTH_TOKEN || "";
  if (!adminToken) {
    throw new Error("Missing INSTANT_ADMIN_TOKEN");
  }
  return { appId, adminToken };
}
function getAdminDb() {
  const { appId, adminToken } = getCredentials();
  return init({ appId, adminToken });
}
function parseBody(raw) {
  if (!raw) return null;
  if (typeof raw === "object") return raw;
  if (typeof raw === "string") {
    try {
      return JSON.parse(raw);
    } catch {
      return null;
    }
  }
  return null;
}
function extractBearerToken(req) {
  const authHeader = req.headers["authorization"] || req.headers["token"];
  const raw = Array.isArray(authHeader) ? authHeader[0] : authHeader;
  if (!raw) return null;
  if (raw.startsWith("Bearer ")) return raw.slice(7).trim();
  return raw.trim();
}
function verifyCronSecret(req) {
  const cronSecret = process.env.CRON_SECRET;
  if (!cronSecret) return true;
  const authHeader = req.headers["authorization"];
  const token = Array.isArray(authHeader) ? authHeader[0] : authHeader;
  return token === `Bearer ${cronSecret}`;
}

// api/_lib/export/auth.js
async function verifyRequestUser(req) {
  const token = extractBearerToken(req);
  if (!token) {
    const err = new Error("Missing authorization token");
    err.status = 401;
    throw err;
  }
  const adminDb = getAdminDb();
  const user = await adminDb.auth.verifyToken(token);
  if (!user?.id) {
    const err = new Error("Invalid or expired token");
    err.status = 401;
    throw err;
  }
  return { userId: user.id, email: user.email ?? "" };
}
async function loadProfileContext(userId) {
  const adminDb = getAdminDb();
  const result = await adminDb.query({
    profiles: {
      $: { where: { userId } },
      stores: {},
      roleDefinition: {}
    },
    roleDefinitions: {}
  });
  const profile = result.profiles?.[0];
  if (!profile) {
    const err = new Error("Profile not found");
    err.status = 403;
    throw err;
  }
  if (profile.approvalStatus !== "approved") {
    const err = new Error("Account not approved");
    err.status = 403;
    throw err;
  }
  const storeIds = (profile.stores ?? []).map((s) => s.id);
  const roleDefinition = profile.roleDefinition ?? (result.roleDefinitions ?? []).find((d) => d.key === profile.role && d.active !== false);
  return {
    profileId: profile.id,
    userId: profile.userId,
    role: profile.role,
    roleDefinition: roleDefinition ?? null,
    approvalStatus: profile.approvalStatus,
    displayName: profile.displayName ?? "",
    email: profile.email ?? "",
    storeIds,
    stores: profile.stores ?? []
  };
}
async function authenticateExportRequest(req) {
  const { userId, email } = await verifyRequestUser(req);
  const ctx = await loadProfileContext(userId);
  return { ...ctx, email };
}

// api/_lib/export/role-capabilities.js
var DEFAULT_CAPS = {
  owner: { canExportDashboard: true, canExportReviewStatus: false },
  admin: { canExportDashboard: true, canExportReviewStatus: false },
  areaManager: { canExportDashboard: true, canExportReviewStatus: false },
  manager: { canExportDashboard: false, canExportReviewStatus: true },
  leader: { canExportDashboard: false, canExportReviewStatus: true },
  subleader: { canExportDashboard: false, canExportReviewStatus: true },
  staff: { canExportDashboard: false, canExportReviewStatus: false },
  viewer: { canExportDashboard: false, canExportReviewStatus: false }
};
function getRoleCapabilities(role, roleDefinition) {
  if (roleDefinition) {
    return {
      canExportDashboard: !!roleDefinition.canExportDashboard,
      canExportReviewStatus: !!roleDefinition.canExportReviewStatus
    };
  }
  return DEFAULT_CAPS[role] ?? { canExportDashboard: false, canExportReviewStatus: false };
}

// api/_lib/export/rbac.js
function assertDashboardExportRole(role, roleDefinition) {
  const caps = getRoleCapabilities(role, roleDefinition);
  if (!caps.canExportDashboard) {
    const err = new Error("Forbidden: dashboard export requires canExportDashboard capability");
    err.status = 403;
    throw err;
  }
}
function assertReviewStatusExportRole(role, roleDefinition) {
  const caps = getRoleCapabilities(role, roleDefinition);
  if (!caps.canExportReviewStatus) {
    const err = new Error("Forbidden: review status export requires canExportReviewStatus capability");
    err.status = 403;
    throw err;
  }
}
function assertExportJobAccess(role, exportType, roleDefinition) {
  if (exportType === "dashboard" || exportType === "failure_history") {
    assertDashboardExportRole(role, roleDefinition);
  } else if (exportType === "review_status") {
    assertReviewStatusExportRole(role, roleDefinition);
  } else {
    const err = new Error("Invalid export type");
    err.status = 400;
    throw err;
  }
}

// api/_lib/export/scope.js
var MASTER_ROLES = /* @__PURE__ */ new Set(["owner", "admin", "areaManager"]);
function resolveDashboardScope(profileCtx, params) {
  const { role, storeIds: assignedStoreIds } = profileCtx;
  const scope = params.scope === "full_history" ? "full_history" : "filtered";
  const filterStoreId = params.filterStoreId === "all" || !params.filterStoreId ? "all" : params.filterStoreId;
  let allowedStoreIds = null;
  if (MASTER_ROLES.has(role)) {
    if (filterStoreId !== "all") {
      allowedStoreIds = [filterStoreId];
    }
  } else {
    allowedStoreIds = assignedStoreIds;
    if (filterStoreId !== "all" && assignedStoreIds.includes(filterStoreId)) {
      allowedStoreIds = [filterStoreId];
    }
  }
  const dateFilter = scope === "full_history" ? null : {
    startDate: params.startDate,
    endDate: params.endDate
  };
  if (scope === "filtered" && (!params.startDate || !params.endDate)) {
    const err = new Error("startDate and endDate required for filtered scope");
    err.status = 400;
    throw err;
  }
  return {
    scope,
    allowedStoreIds,
    dateFilter,
    filterStoreId,
    storeScopeJson: JSON.stringify({
      allowedStoreIds,
      filterStoreId,
      scope
    }),
    dateRangeJson: JSON.stringify(
      dateFilter ?? { startDate: null, endDate: null, allTime: true }
    )
  };
}
function resolveReviewStatusScope(profileCtx, params) {
  const { storeIds: assignedStoreIds } = profileCtx;
  if (!assignedStoreIds.length) {
    const err = new Error("No stores assigned to this user");
    err.status = 403;
    throw err;
  }
  const scope = params.scope === "all_assigned" ? "all_assigned" : "current_list";
  const daysBack = Number(params.daysBack) > 0 ? Number(params.daysBack) : 30;
  const limit = scope === "current_list" ? Number(params.limit) > 0 ? Number(params.limit) : 200 : null;
  return {
    scope,
    allowedStoreIds: assignedStoreIds,
    daysBack: scope === "current_list" ? daysBack : null,
    limit,
    storeScopeJson: JSON.stringify({ allowedStoreIds: assignedStoreIds }),
    dateRangeJson: JSON.stringify(
      scope === "current_list" ? { daysBack, limit } : { allTime: true }
    )
  };
}
function filterReportsByStore(reports, allowedStoreIds) {
  if (!allowedStoreIds) return reports;
  const set = new Set(allowedStoreIds);
  return reports.filter((r) => set.has(r.storeId));
}

// api/_lib/export/audit.js
import { id } from "@instantdb/admin";
async function logExportRequested({
  userId,
  role,
  exportType,
  format,
  dateRangeJson,
  storeScopeJson,
  paramsJson,
  jobId
}) {
  const adminDb = getAdminDb();
  const logId = id();
  const now = (/* @__PURE__ */ new Date()).toISOString();
  await adminDb.transact(
    adminDb.tx.exportAuditLogs[logId].update({
      userId,
      role,
      exportType,
      format,
      dateRangeJson: dateRangeJson ?? "{}",
      storeScopeJson: storeScopeJson ?? "{}",
      paramsJson: paramsJson ?? "{}",
      rowCount: 0,
      truncated: false,
      jobId,
      status: "requested",
      downloadAt: "",
      createdAt: now
    })
  );
  return logId;
}
async function logExportCompleted(jobId, { rowCount, truncated }) {
  const adminDb = getAdminDb();
  const result = await adminDb.query({
    exportAuditLogs: { $: { where: { jobId, status: "requested" } } }
  });
  const log = result.exportAuditLogs?.[0];
  if (!log) return;
  await adminDb.transact(
    adminDb.tx.exportAuditLogs[log.id].update({
      status: "completed",
      rowCount: rowCount ?? 0,
      truncated: truncated ?? false
    })
  );
}
async function logExportFailed(jobId, errorMessage) {
  const adminDb = getAdminDb();
  const result = await adminDb.query({
    exportAuditLogs: { $: { where: { jobId, status: "requested" } } }
  });
  const log = result.exportAuditLogs?.[0];
  if (!log) return;
  await adminDb.transact(
    adminDb.tx.exportAuditLogs[log.id].update({
      status: "failed",
      paramsJson: JSON.stringify({ error: errorMessage })
    })
  );
}
async function logExportDownloaded(jobId) {
  const adminDb = getAdminDb();
  const result = await adminDb.query({
    exportAuditLogs: { $: { where: { jobId } } }
  });
  const log = result.exportAuditLogs?.[0];
  if (!log) return;
  await adminDb.transact(
    adminDb.tx.exportAuditLogs[log.id].update({
      status: "downloaded",
      downloadAt: (/* @__PURE__ */ new Date()).toISOString()
    })
  );
}

// api/_lib/export/csv-builder.js
var ROW_CAP = 1e5;
var TRUNCATION_WARNING = "# WARNING: Results truncated at 100,000 rows";
function escapeCell(value) {
  if (value == null) return "";
  const str = String(value);
  if (str.includes('"') || str.includes(",") || str.includes("\n") || str.includes("\r")) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}
function buildCsv(headers, rows, options = {}) {
  const { emptyMessage = "# No data for selected scope" } = options;
  const truncated = rows.length > ROW_CAP;
  const dataRows = truncated ? rows.slice(0, ROW_CAP) : rows;
  const lines = [];
  if (truncated) {
    lines.push(TRUNCATION_WARNING);
  }
  if (dataRows.length === 0) {
    lines.push(emptyMessage);
  }
  lines.push(headers.map(escapeCell).join(","));
  for (const row of dataRows) {
    lines.push(headers.map((h) => escapeCell(row[h])).join(","));
  }
  const csv = "\uFEFF" + lines.join("\r\n");
  return {
    csv,
    rowCount: dataRows.length,
    truncated,
    warningHeader: truncated ? TRUNCATION_WARNING : ""
  };
}

// api/_lib/export/queries.js
async function fetchReportsWithResponses(allowedStoreIds, dateFilter) {
  const adminDb = getAdminDb();
  const query = {
    reports: {
      responses: {}
    }
  };
  if (dateFilter?.startDate && dateFilter?.endDate) {
    query.reports.$ = {
      where: {
        reportDate: { $gte: dateFilter.startDate, $lte: dateFilter.endDate }
      }
    };
  }
  const result = await adminDb.query(query);
  let reports = result.reports ?? [];
  reports = filterReportsByStore(reports, allowedStoreIds);
  if (!dateFilter && allowedStoreIds?.length) {
    reports = filterReportsByStore(reports, allowedStoreIds);
  } else if (!dateFilter) {
    reports = filterReportsByStore(reports, null);
  }
  return reports;
}
async function fetchReviewStatusData(allowedStoreIds) {
  const adminDb = getAdminDb();
  const result = await adminDb.query({
    reports: { responses: {} },
    reviewEvents: {},
    profiles: {}
  });
  const reports = filterReportsByStore(result.reports ?? [], allowedStoreIds);
  return {
    reports,
    reviewEvents: result.reviewEvents ?? [],
    profiles: result.profiles ?? []
  };
}
async function fetchMediaByResponseIds(responseIds) {
  if (!responseIds.length) return {};
  const adminDb = getAdminDb();
  const result = await adminDb.query({
    mediaRecords: {}
  });
  const map = {};
  for (const m of result.mediaRecords ?? []) {
    if (!responseIds.includes(m.reportResponseId)) continue;
    if (!map[m.reportResponseId]) map[m.reportResponseId] = [];
    map[m.reportResponseId].push(m);
  }
  return map;
}

// api/_lib/export/row-mappers.js
function mediaStorageDeleted(mediaList) {
  if (!mediaList?.length) return false;
  return mediaList.every((m) => m.storageDeleted === true);
}
function mapDashboardRows(reports, mediaByResponseId = {}) {
  const rows = [];
  for (const report of reports) {
    const responses = report.responses ?? [];
    if (!responses.length) {
      rows.push({
        report_id: report.id,
        report_date: report.reportDate,
        store_code: report.storeCode,
        store_name: report.storeName,
        template_name: report.templateName,
        report_status: report.status,
        completion_percent: report.completionPercent ?? 0,
        compliance_percent: report.compliancePercent ?? 0,
        item_section: "",
        item_title: "",
        item_status: "",
        feedback_code: "",
        feedback_note: "",
        approved_at: "",
        media_storage_deleted: "",
        submitted_by_role: report.submittedByRole ?? ""
      });
      continue;
    }
    for (const resp of responses) {
      const media = mediaByResponseId[resp.id] ?? [];
      rows.push({
        report_id: report.id,
        report_date: report.reportDate,
        store_code: report.storeCode,
        store_name: report.storeName,
        template_name: report.templateName,
        report_status: report.status,
        completion_percent: report.completionPercent ?? 0,
        compliance_percent: report.compliancePercent ?? 0,
        item_section: resp.section ?? "",
        item_title: resp.title ?? "",
        item_status: resp.status ?? "",
        feedback_code: resp.feedbackCode ?? "",
        feedback_note: resp.feedbackNote || resp.rejectionReason || "",
        approved_at: resp.approvedAt ?? "",
        media_storage_deleted: media.length ? mediaStorageDeleted(media) : "",
        submitted_by_role: report.submittedByRole ?? ""
      });
    }
  }
  return rows;
}
var DASHBOARD_CSV_HEADERS = [
  "report_id",
  "report_date",
  "store_code",
  "store_name",
  "template_name",
  "report_status",
  "completion_percent",
  "compliance_percent",
  "item_section",
  "item_title",
  "item_status",
  "feedback_code",
  "feedback_note",
  "approved_at",
  "media_storage_deleted",
  "submitted_by_role"
];
function mapReviewStatusRows(statusRows) {
  return statusRows.map((row) => ({
    report_date: row.reportDate,
    store_code: row.storeCode,
    submitted_by: row.submittedBy,
    submitted_time: row.submittedTime,
    status: row.status,
    latest_review_time: row.latestReviewTime,
    latest_feedback: row.latestFeedback,
    finalized_time: row.finalizedTime,
    lead_time_ms: row.leadTimeMs ?? "",
    correction_duration_ms: row.correctionDurationMs ?? ""
  }));
}
var REVIEW_STATUS_CSV_HEADERS = [
  "report_date",
  "store_code",
  "submitted_by",
  "submitted_time",
  "status",
  "latest_review_time",
  "latest_feedback",
  "finalized_time",
  "lead_time_ms",
  "correction_duration_ms"
];
function msToMinutes(ms) {
  if (ms == null || ms < 0) return "";
  return Math.round(ms / 6e4);
}
function mapFailureHistoryRows(instances) {
  return instances.map((inst) => ({
    report_id: inst.reportId,
    report_date: inst.reportDate,
    store_code: inst.storeCode,
    template_name: inst.templateName,
    report_response_id: inst.reportResponseId,
    template_item_id: inst.templateItemId,
    item_title: inst.itemTitle,
    section: inst.section,
    category: inst.category,
    issue_type: inst.issueType,
    issue_at: inst.issueAt,
    issue_by_user_id: inst.issueByUserId,
    issue_by_name: inst.issueByName,
    issue_by_role: inst.issueByRole,
    rejection_reason: inst.rejectionReason,
    feedback_code: inst.feedbackCode,
    feedback_note: inst.feedbackNote,
    original_submitted_by_user_id: inst.originalSubmittedByUserId,
    original_submitted_by_role: inst.originalSubmittedByRole,
    original_submitted_at: inst.originalSubmittedAt,
    resubmitted_at: inst.resubmittedAt,
    resubmitted_by_user_id: inst.resubmittedByUserId,
    resubmitted_by_name: inst.resubmittedByName,
    resubmitted_by_role: inst.resubmittedByRole,
    correction_duration_minutes: msToMinutes(inst.correctionDurationMs),
    next_review_at: inst.nextReviewAt,
    next_review_by_user_id: inst.nextReviewByUserId,
    next_review_by_name: inst.nextReviewByName,
    next_review_by_role: inst.nextReviewByRole,
    next_review_decision: inst.nextReviewDecision,
    rereview_duration_minutes: msToMinutes(inst.rereviewDurationMs),
    final_approved_at: inst.finalApprovedAt,
    final_approved_by_user_id: inst.finalApprovedByUserId,
    final_approved_by_name: inst.finalApprovedByName,
    final_approved_by_role: inst.finalApprovedByRole,
    time_to_final_approval_minutes: msToMinutes(inst.timeToFinalApprovalMs),
    cycle_number: inst.cycleNumber,
    current_status: inst.currentStatus,
    report_final_status: inst.reportFinalStatus
  }));
}
var FAILURE_HISTORY_CSV_HEADERS = [
  "report_id",
  "report_date",
  "store_code",
  "template_name",
  "report_response_id",
  "template_item_id",
  "item_title",
  "section",
  "category",
  "issue_type",
  "issue_at",
  "issue_by_user_id",
  "issue_by_name",
  "issue_by_role",
  "rejection_reason",
  "feedback_code",
  "feedback_note",
  "original_submitted_by_user_id",
  "original_submitted_by_role",
  "original_submitted_at",
  "resubmitted_at",
  "resubmitted_by_user_id",
  "resubmitted_by_name",
  "resubmitted_by_role",
  "correction_duration_minutes",
  "next_review_at",
  "next_review_by_user_id",
  "next_review_by_name",
  "next_review_by_role",
  "next_review_decision",
  "rereview_duration_minutes",
  "final_approved_at",
  "final_approved_by_user_id",
  "final_approved_by_name",
  "final_approved_by_role",
  "time_to_final_approval_minutes",
  "cycle_number",
  "current_status",
  "report_final_status"
];

// api/_lib/export/generators/dashboard-csv.js
async function generateDashboardCsv(profileCtx, params) {
  const scopeResult = resolveDashboardScope(profileCtx, params);
  const { allowedStoreIds, dateFilter } = scopeResult;
  const reports = await fetchReportsWithResponses(allowedStoreIds, dateFilter);
  const responseIds = [];
  for (const r of reports) {
    for (const resp of r.responses ?? []) {
      responseIds.push(resp.id);
    }
  }
  const mediaByResponseId = await fetchMediaByResponseIds(responseIds);
  const rows = mapDashboardRows(reports, mediaByResponseId);
  const result = buildCsv(DASHBOARD_CSV_HEADERS, rows);
  return {
    ...result,
    scopeResult,
    reports
  };
}

// api/_lib/export/review-status-rows.js
var STATUS_ORDER = {
  waiting_approval: 0,
  need_correction: 1,
  rejected: 2,
  approved: 3
};
function parseMs(iso) {
  if (!iso?.trim()) return null;
  const ms = new Date(iso).getTime();
  return Number.isNaN(ms) ? null : ms;
}
function formatDisplay(iso) {
  if (!iso?.trim()) return "\u2014";
  try {
    return new Date(iso).toLocaleString("en-GB", {
      day: "2-digit",
      month: "short",
      year: "numeric",
      hour: "2-digit",
      minute: "2-digit"
    });
  } catch {
    return iso;
  }
}
function resolveSubmitterName(report, profiles) {
  const profile = profiles.find((p) => p.userId === report.submittedByUserId);
  if (profile?.displayName?.trim()) return profile.displayName.trim();
  if (profile?.email) return profile.email.split("@")[0] ?? profile.email;
  return report.submittedByRole || "\u2014";
}
function latestReviewIso(report, events) {
  const responses = report.responses ?? [];
  const responseTimes = responses.map((r) => r.approvedAt).filter((t) => t?.trim());
  const reviewEventTypes = /* @__PURE__ */ new Set([
    "item_approved",
    "item_rejected",
    "item_correction",
    "report_finalized"
  ]);
  const eventTimes = events.filter((e) => e.reportId === report.id && reviewEventTypes.has(e.eventType)).map((e) => e.createdAt);
  const all = [...responseTimes, ...eventTimes].sort((a, b) => b.localeCompare(a));
  return all[0] ?? null;
}
function latestFeedbackNote(report, events) {
  const responses = report.responses ?? [];
  const flagged = responses.filter(
    (r) => ["rejected", "need_correction"].includes(r.status) && r.rejectionReason?.trim()
  );
  if (flagged.length) {
    const sorted = [...flagged].sort(
      (a, b) => (b.updatedAt || b.approvedAt || "").localeCompare(a.updatedAt || a.approvedAt || "")
    );
    return sorted[0].rejectionReason.trim();
  }
  const feedbackEvents = events.filter(
    (e) => e.reportId === report.id && (e.eventType === "item_correction" || e.eventType === "item_rejected") && e.note?.trim()
  ).sort((a, b) => b.createdAt.localeCompare(a.createdAt));
  return feedbackEvents[0]?.note?.trim() ?? "";
}
function computeCorrectionDurationMs(events, reportId) {
  const reportEvents = events.filter((e) => e.reportId === reportId).sort((a, b) => a.createdAt.localeCompare(b.createdAt));
  let maxGap = null;
  for (let i = 0; i < reportEvents.length; i++) {
    const ev = reportEvents[i];
    if (ev.eventType !== "item_correction" && ev.eventType !== "item_rejected") continue;
    const correctionMs = parseMs(ev.createdAt);
    if (correctionMs == null) continue;
    const resubmit = reportEvents.slice(i + 1).find((e) => e.eventType === "resubmitted" && e.createdAt > ev.createdAt);
    if (!resubmit) continue;
    const resubmitMs = parseMs(resubmit.createdAt);
    if (resubmitMs == null) continue;
    const gap = resubmitMs - correctionMs;
    if (gap >= 0 && (maxGap == null || gap > maxGap)) {
      maxGap = gap;
    }
  }
  return maxGap;
}
function isWithinDateWindow(reportDate, daysBack) {
  if (!reportDate?.trim()) return false;
  const end = /* @__PURE__ */ new Date();
  const start = /* @__PURE__ */ new Date();
  start.setDate(start.getDate() - daysBack);
  const startStr = start.toISOString().slice(0, 10);
  const endStr = end.toISOString().slice(0, 10);
  return reportDate >= startStr && reportDate <= endStr;
}
function sortReports(a, b) {
  const orderA = STATUS_ORDER[a.status] ?? 99;
  const orderB = STATUS_ORDER[b.status] ?? 99;
  if (orderA !== orderB) return orderA - orderB;
  return (b.submittedAt ?? "").localeCompare(a.submittedAt ?? "");
}
function buildReportTimeline(report, events) {
  const reportEvents = events.filter((e) => e.reportId === report.id);
  const finalized = [...reportEvents].reverse().find((e) => e.eventType === "report_finalized");
  const firstSubmitted = reportEvents.find((e) => e.eventType === "submitted") ?? (report.submittedAt ? { createdAt: report.submittedAt } : null);
  const firstMs = firstSubmitted ? parseMs(firstSubmitted.createdAt) : null;
  const endMs = finalized ? parseMs(finalized.createdAt) : null;
  const totalDurationMs = firstMs != null && endMs != null ? endMs - firstMs : null;
  return {
    finalizedAt: finalized?.createdAt ?? null,
    totalDurationMs,
    source: reportEvents.length > 0 ? "events" : "inferred"
  };
}
function buildReviewStatusRows(reports, profiles, events, options) {
  const { daysBack = 30, limit = 200, scope = "current_list" } = options;
  let filtered = [...reports];
  if (scope === "current_list") {
    filtered = filtered.filter((r) => isWithinDateWindow(r.reportDate, daysBack)).sort(sortReports).slice(0, limit);
  }
  return filtered.map((report) => {
    const reportEvents = events.filter((e) => e.reportId === report.id);
    const timeline = buildReportTimeline(report, reportEvents);
    const latestReview = latestReviewIso(report, reportEvents);
    return {
      report,
      reportDate: report.reportDate,
      storeCode: report.storeCode,
      submittedBy: resolveSubmitterName(report, profiles),
      submittedTime: formatDisplay(report.submittedAt),
      status: report.status,
      latestReviewTime: formatDisplay(latestReview ?? void 0),
      latestFeedback: latestFeedbackNote(report, reportEvents),
      finalizedTime: timeline.finalizedAt ? formatDisplay(timeline.finalizedAt) : "\u2014",
      leadTimeMs: timeline.totalDurationMs,
      correctionDurationMs: computeCorrectionDurationMs(events, report.id),
      timelineSource: timeline.source
    };
  });
}
function computeDashboardKpis(reports) {
  if (!reports.length) {
    return {
      reportCount: 0,
      avgCompletion: 0,
      avgCompliance: 0,
      failedItemCount: 0
    };
  }
  const completion = Math.round(
    reports.reduce((sum, r) => sum + (r.completionPercent ?? 0), 0) / reports.length
  );
  const compliance = Math.round(
    reports.reduce((sum, r) => sum + (r.compliancePercent ?? 0), 0) / reports.length
  );
  const failSet = /* @__PURE__ */ new Set();
  for (const report of reports) {
    for (const resp of report.responses ?? []) {
      if (resp.status === "rejected") failSet.add(resp.title);
    }
  }
  return {
    reportCount: reports.length,
    avgCompletion: completion,
    avgCompliance: compliance,
    failedItemCount: failSet.size
  };
}

// api/_lib/export/generators/review-status-csv.js
async function generateReviewStatusCsv(profileCtx, params) {
  const scopeResult = resolveReviewStatusScope(profileCtx, params);
  const { allowedStoreIds, daysBack, limit, scope } = scopeResult;
  const { reports, reviewEvents, profiles } = await fetchReviewStatusData(allowedStoreIds);
  const statusRows = buildReviewStatusRows(reports, profiles, reviewEvents, {
    daysBack: daysBack ?? 30,
    limit: limit ?? 200,
    scope
  });
  const rows = mapReviewStatusRows(statusRows);
  const result = buildCsv(REVIEW_STATUS_CSV_HEADERS, rows);
  return {
    ...result,
    scopeResult,
    statusRows,
    reports
  };
}

// api/_lib/export/failure-history-aggregate.js
var DECISION_TYPES = /* @__PURE__ */ new Set(["item_approved", "item_rejected", "item_correction"]);
var ISSUE_TYPES = /* @__PURE__ */ new Set(["item_rejected", "item_correction"]);
function parseMs2(iso) {
  if (!iso?.trim()) return null;
  const ms = new Date(iso).getTime();
  return Number.isNaN(ms) ? null : ms;
}
function dateInRange(iso, from, to) {
  const d = iso.slice(0, 10);
  return d >= from && d <= to;
}
function actorName(userId, snapshot, profiles) {
  if (snapshot?.trim()) return snapshot.trim();
  const p = profiles.find((x) => x.userId === userId);
  if (p?.displayName?.trim()) return p.displayName.trim();
  if (p?.email) return p.email.split("@")[0] ?? p.email;
  if (userId) return `Former user \u2014 ${userId.slice(0, 8)}`;
  return "Unknown";
}
function dedupeEvents(events) {
  const seen = /* @__PURE__ */ new Set();
  const out = [];
  for (const e of events) {
    const key = `${e.reportResponseId}|${e.eventType}|${e.createdAt}|${e.actorUserId}`;
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(e);
  }
  return out;
}
function buildIssueInstancesForExport(events, reports, profiles) {
  const responsesById = /* @__PURE__ */ new Map();
  for (const report of reports) {
    for (const resp of report.responses ?? []) {
      responsesById.set(resp.id, { ...resp, report });
    }
  }
  const reportById = new Map(reports.map((r) => [r.id, r]));
  const sorted = dedupeEvents([...events]).sort((a, b) => a.createdAt.localeCompare(b.createdAt));
  const instances = [];
  const issueCountByResponse = /* @__PURE__ */ new Map();
  for (const ev of sorted) {
    if (!ISSUE_TYPES.has(ev.eventType) || !ev.reportResponseId) continue;
    const respMeta = responsesById.get(ev.reportResponseId);
    const report = reportById.get(ev.reportId);
    const cycleNum = (issueCountByResponse.get(ev.reportResponseId) ?? 0) + 1;
    issueCountByResponse.set(ev.reportResponseId, cycleNum);
    const responseEvents = sorted.filter((e) => e.reportResponseId === ev.reportResponseId);
    const afterIssue = responseEvents.filter((e) => e.createdAt > ev.createdAt);
    const resubmit = afterIssue.find((e) => e.eventType === "resubmitted");
    const nextDecision = afterIssue.find((e) => DECISION_TYPES.has(e.eventType));
    const finalApproval = afterIssue.find((e) => e.eventType === "item_approved");
    const firstSubmit = responseEvents.find((e) => e.eventType === "submitted");
    const issueMs = parseMs2(ev.createdAt);
    const resubmitMs = resubmit ? parseMs2(resubmit.createdAt) : null;
    const nextDecisionMs = nextDecision ? parseMs2(nextDecision.createdAt) : null;
    const finalApprovalMs = finalApproval ? parseMs2(finalApproval.createdAt) : null;
    instances.push({
      eventId: ev.id,
      reportId: ev.reportId,
      reportResponseId: ev.reportResponseId,
      templateItemId: ev.templateItemId || respMeta?.templateItemId || "",
      storeId: ev.storeId,
      itemTitle: ev.itemTitle || respMeta?.title || "",
      section: ev.sectionSnapshot || respMeta?.section || "",
      category: ev.categorySnapshot || respMeta?.failureCategory || "",
      issueType: ev.eventType === "item_rejected" ? "rejected" : "need_correction",
      issueAt: ev.createdAt,
      issueByUserId: ev.actorUserId,
      issueByRole: ev.actorRole,
      issueByName: actorName(ev.actorUserId, ev.actorDisplayNameSnapshot, profiles),
      rejectionReason: ev.note || "",
      feedbackCode: ev.feedbackCode || "",
      feedbackNote: ev.feedbackNote || "",
      resubmittedAt: resubmit?.createdAt ?? "",
      resubmittedByUserId: resubmit?.actorUserId ?? "",
      resubmittedByRole: resubmit?.actorRole ?? "",
      resubmittedByName: resubmit ? actorName(resubmit.actorUserId, resubmit.actorDisplayNameSnapshot, profiles) : "",
      correctionDurationMs: issueMs != null && resubmitMs != null ? resubmitMs - issueMs : null,
      nextReviewAt: nextDecision?.createdAt ?? "",
      nextReviewByUserId: nextDecision?.actorUserId ?? "",
      nextReviewByRole: nextDecision?.actorRole ?? "",
      nextReviewByName: nextDecision ? actorName(nextDecision.actorUserId, nextDecision.actorDisplayNameSnapshot, profiles) : "",
      nextReviewDecision: nextDecision?.statusAfter ?? "",
      rereviewDurationMs: resubmitMs != null && nextDecisionMs != null ? nextDecisionMs - resubmitMs : null,
      finalApprovedAt: finalApproval?.createdAt ?? "",
      finalApprovedByUserId: finalApproval?.actorUserId ?? "",
      finalApprovedByRole: finalApproval?.actorRole ?? "",
      finalApprovedByName: finalApproval ? actorName(finalApproval.actorUserId, finalApproval.actorDisplayNameSnapshot, profiles) : "",
      timeToFinalApprovalMs: issueMs != null && finalApprovalMs != null ? finalApprovalMs - issueMs : null,
      cycleNumber: cycleNum,
      currentStatus: respMeta?.status ?? "",
      reportFinalStatus: report?.status ?? "",
      reportDate: report?.reportDate ?? "",
      storeCode: report?.storeCode ?? "",
      templateName: report?.templateName ?? "",
      originalSubmittedByUserId: firstSubmit?.actorUserId || respMeta?.submittedByUserId || report?.submittedByUserId || "",
      originalSubmittedByRole: firstSubmit?.actorRole || respMeta?.submittedByRole || report?.submittedByRole || "",
      originalSubmittedAt: firstSubmit?.createdAt ?? respMeta?.submittedAt ?? report?.submittedAt ?? ""
    });
  }
  return instances;
}
function filterIssueInstances(instances, filters) {
  return instances.filter((inst) => {
    if (!dateInRange(inst.issueAt, filters.startDate, filters.endDate)) return false;
    if (filters.storeIds?.length && !filters.storeIds.includes(inst.storeId)) return false;
    return true;
  });
}

// api/_lib/export/generators/failure-history-csv.js
async function generateFailureHistoryCsv(profileCtx, params) {
  const scopeResult = resolveDashboardScope(profileCtx, params);
  const { allowedStoreIds, dateFilter } = scopeResult;
  const { reports, reviewEvents, profiles } = await fetchReviewStatusData(allowedStoreIds);
  const allInstances = buildIssueInstancesForExport(reviewEvents, reports, profiles);
  const instances = dateFilter?.startDate && dateFilter?.endDate ? filterIssueInstances(allInstances, {
    startDate: dateFilter.startDate,
    endDate: dateFilter.endDate,
    storeIds: allowedStoreIds
  }) : allInstances.filter((inst) => {
    if (allowedStoreIds?.length && !allowedStoreIds.includes(inst.storeId)) return false;
    return true;
  });
  const rows = mapFailureHistoryRows(instances);
  const result = buildCsv(FAILURE_HISTORY_CSV_HEADERS, rows);
  return {
    ...result,
    scopeResult,
    reports,
    instances
  };
}

// api/_lib/export/storage.js
async function uploadExportFile(jobId, format, content) {
  const adminDb = getAdminDb();
  const ext = format === "pdf" ? "pdf" : "csv";
  const path = `exports/${jobId}.${ext}`;
  const contentType = format === "pdf" ? "application/pdf" : "text/csv; charset=utf-8";
  const buffer = Buffer.isBuffer(content) ? content : Buffer.from(content, format === "pdf" ? void 0 : "utf8");
  const { data: fileData } = await adminDb.storage.uploadFile(path, buffer, {
    contentType
  });
  if (!fileData?.id) throw new Error("Export upload returned no file ID");
  const filesResult = await adminDb.query({
    $files: { $: { where: { id: fileData.id } } }
  });
  const downloadUrl = filesResult?.$files?.[0]?.url ?? "";
  return { filePath: path, downloadUrl, fileId: fileData.id };
}

// api/_lib/export/pdf/render-pdf.js
import React3 from "react";
import { renderToBuffer } from "@react-pdf/renderer";

// api/_lib/export/pdf/DashboardPdfDocument.js
import React from "react";
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
var styles = StyleSheet.create({
  page: { padding: 32, fontSize: 9, fontFamily: "Helvetica" },
  title: { fontSize: 16, marginBottom: 8, fontFamily: "Helvetica-Bold" },
  subtitle: { fontSize: 10, marginBottom: 16, color: "#444" },
  kpiRow: { flexDirection: "row", marginBottom: 16, gap: 12 },
  kpiBox: { flex: 1, padding: 8, backgroundColor: "#f5f5f5", borderRadius: 4 },
  kpiLabel: { fontSize: 8, color: "#666" },
  kpiValue: { fontSize: 14, fontFamily: "Helvetica-Bold", marginTop: 2 },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#333",
    color: "#fff",
    padding: 4,
    fontFamily: "Helvetica-Bold",
    fontSize: 7
  },
  tableRow: { flexDirection: "row", borderBottomWidth: 0.5, borderColor: "#ddd", padding: 3, fontSize: 7 },
  colDate: { width: "12%" },
  colStore: { width: "10%" },
  colTemplate: { width: "18%" },
  colStatus: { width: "12%" },
  colPct: { width: "10%" },
  colItem: { width: "20%" },
  colItemStatus: { width: "18%" },
  footer: { position: "absolute", bottom: 24, left: 32, right: 32, fontSize: 7, color: "#c00" },
  warning: { backgroundColor: "#fff3cd", padding: 8, marginBottom: 12, fontSize: 8, color: "#856404" }
});
function formatScopeLabel(params) {
  if (params.scope === "full_history") return "Full accessible history";
  return `${params.startDate ?? ""} \u2014 ${params.endDate ?? ""}`;
}
function DashboardPdfDocument({ params, reports, kpis, mediaExpiryFooter }) {
  const rows = [];
  for (const report of reports.slice(0, 500)) {
    const responses = report.responses ?? [];
    if (!responses.length) {
      rows.push({ report, resp: null });
    } else {
      for (const resp of responses.slice(0, 20)) {
        rows.push({ report, resp });
      }
    }
  }
  return React.createElement(
    Document,
    null,
    React.createElement(
      Page,
      { size: "A4", style: styles.page },
      React.createElement(Text, { style: styles.title }, "Operation Dashboard Export"),
      React.createElement(Text, { style: styles.subtitle }, `Period: ${formatScopeLabel(params)}`),
      React.createElement(
        View,
        { style: styles.warning },
        React.createElement(Text, null, mediaExpiryFooter)
      ),
      React.createElement(
        View,
        { style: styles.kpiRow },
        React.createElement(
          View,
          { style: styles.kpiBox },
          React.createElement(Text, { style: styles.kpiLabel }, "Total Reports"),
          React.createElement(Text, { style: styles.kpiValue }, String(kpis.reportCount))
        ),
        React.createElement(
          View,
          { style: styles.kpiBox },
          React.createElement(Text, { style: styles.kpiLabel }, "Avg Completion"),
          React.createElement(Text, { style: styles.kpiValue }, `${kpis.avgCompletion}%`)
        ),
        React.createElement(
          View,
          { style: styles.kpiBox },
          React.createElement(Text, { style: styles.kpiLabel }, "Avg Compliance"),
          React.createElement(Text, { style: styles.kpiValue }, `${kpis.avgCompliance}%`)
        ),
        React.createElement(
          View,
          { style: styles.kpiBox },
          React.createElement(Text, { style: styles.kpiLabel }, "Failed Items"),
          React.createElement(Text, { style: styles.kpiValue }, String(kpis.failedItemCount))
        )
      ),
      React.createElement(
        View,
        { style: styles.tableHeader },
        React.createElement(Text, { style: styles.colDate }, "Date"),
        React.createElement(Text, { style: styles.colStore }, "Store"),
        React.createElement(Text, { style: styles.colTemplate }, "Template"),
        React.createElement(Text, { style: styles.colStatus }, "Status"),
        React.createElement(Text, { style: styles.colPct }, "Complete"),
        React.createElement(Text, { style: styles.colItem }, "Item"),
        React.createElement(Text, { style: styles.colItemStatus }, "Item Status")
      ),
      ...rows.map(
        ({ report, resp }, i) => React.createElement(
          View,
          { key: i, style: styles.tableRow },
          React.createElement(Text, { style: styles.colDate }, report.reportDate),
          React.createElement(Text, { style: styles.colStore }, report.storeCode),
          React.createElement(Text, { style: styles.colTemplate }, report.templateName),
          React.createElement(Text, { style: styles.colStatus }, report.status),
          React.createElement(Text, { style: styles.colPct }, `${report.completionPercent ?? 0}%`),
          React.createElement(Text, { style: styles.colItem }, resp?.title ?? "\u2014"),
          React.createElement(Text, { style: styles.colItemStatus }, resp?.status ?? "\u2014")
        )
      ),
      React.createElement(Text, { style: styles.footer, fixed: true }, mediaExpiryFooter)
    )
  );
}

// api/_lib/export/pdf/ReviewStatusPdfDocument.js
import React2 from "react";
import { Document as Document2, Page as Page2, Text as Text2, View as View2, StyleSheet as StyleSheet2 } from "@react-pdf/renderer";
var styles2 = StyleSheet2.create({
  page: { padding: 32, fontSize: 9, fontFamily: "Helvetica" },
  title: { fontSize: 16, marginBottom: 8, fontFamily: "Helvetica-Bold" },
  subtitle: { fontSize: 10, marginBottom: 16, color: "#444" },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#333",
    color: "#fff",
    padding: 4,
    fontFamily: "Helvetica-Bold",
    fontSize: 7
  },
  tableRow: { flexDirection: "row", borderBottomWidth: 0.5, borderColor: "#ddd", padding: 3, fontSize: 7 },
  colDate: { width: "10%" },
  colStore: { width: "8%" },
  colSubmitter: { width: "12%" },
  colStatus: { width: "10%" },
  colReview: { width: "12%" },
  colFeedback: { width: "18%" },
  colFinal: { width: "12%" },
  colLead: { width: "10%" },
  colCorrection: { width: "8%" },
  footer: { position: "absolute", bottom: 24, left: 32, right: 32, fontSize: 7, color: "#c00" },
  warning: { backgroundColor: "#fff3cd", padding: 8, marginBottom: 12, fontSize: 8, color: "#856404" }
});
function formatScopeLabel2(params) {
  if (params.scope === "all_assigned") return "All assigned reports";
  return `Last ${params.daysBack ?? 30} days`;
}
function formatMs(ms) {
  if (ms == null) return "\u2014";
  const totalMinutes = Math.floor(ms / 6e4);
  const hours = Math.floor(totalMinutes / 60);
  const minutes = totalMinutes % 60;
  if (hours > 0) return `${hours}h ${minutes}m`;
  if (minutes > 0) return `${minutes}m`;
  return "<1m";
}
function ReviewStatusPdfDocument({ params, statusRows, mediaExpiryFooter }) {
  return React2.createElement(
    Document2,
    null,
    React2.createElement(
      Page2,
      { size: "A4", orientation: "landscape", style: styles2.page },
      React2.createElement(Text2, { style: styles2.title }, "Report Review Status Export"),
      React2.createElement(Text2, { style: styles2.subtitle }, formatScopeLabel2(params)),
      React2.createElement(
        View2,
        { style: styles2.warning },
        React2.createElement(Text2, null, mediaExpiryFooter)
      ),
      React2.createElement(
        View2,
        { style: styles2.tableHeader },
        React2.createElement(Text2, { style: styles2.colDate }, "Date"),
        React2.createElement(Text2, { style: styles2.colStore }, "Store"),
        React2.createElement(Text2, { style: styles2.colSubmitter }, "Submitted By"),
        React2.createElement(Text2, { style: styles2.colStatus }, "Status"),
        React2.createElement(Text2, { style: styles2.colReview }, "Latest Review"),
        React2.createElement(Text2, { style: styles2.colFeedback }, "Feedback"),
        React2.createElement(Text2, { style: styles2.colFinal }, "Finalized"),
        React2.createElement(Text2, { style: styles2.colLead }, "Lead Time"),
        React2.createElement(Text2, { style: styles2.colCorrection }, "Correction")
      ),
      ...statusRows.slice(0, 500).map(
        (row, i) => React2.createElement(
          View2,
          { key: i, style: styles2.tableRow },
          React2.createElement(Text2, { style: styles2.colDate }, row.reportDate),
          React2.createElement(Text2, { style: styles2.colStore }, row.storeCode),
          React2.createElement(Text2, { style: styles2.colSubmitter }, row.submittedBy),
          React2.createElement(Text2, { style: styles2.colStatus }, row.status),
          React2.createElement(Text2, { style: styles2.colReview }, row.latestReviewTime),
          React2.createElement(Text2, { style: styles2.colFeedback }, row.latestFeedback || "\u2014"),
          React2.createElement(Text2, { style: styles2.colFinal }, row.finalizedTime),
          React2.createElement(Text2, { style: styles2.colLead }, formatMs(row.leadTimeMs)),
          React2.createElement(Text2, { style: styles2.colCorrection }, formatMs(row.correctionDurationMs))
        )
      ),
      React2.createElement(Text2, { style: styles2.footer, fixed: true }, mediaExpiryFooter)
    )
  );
}

// api/_lib/export/pdf/render-pdf.js
async function renderExportPdf({
  exportType,
  params,
  reports,
  statusRows,
  mediaExpiryFooter
}) {
  let doc;
  if (exportType === "dashboard") {
    const kpis = computeDashboardKpis(reports);
    doc = React3.createElement(DashboardPdfDocument, {
      params,
      reports,
      kpis,
      mediaExpiryFooter
    });
  } else {
    doc = React3.createElement(ReviewStatusPdfDocument, {
      params,
      statusRows,
      mediaExpiryFooter
    });
  }
  return renderToBuffer(doc);
}

// api/_lib/export/job-runner.js
var MEDIA_EXPIRY_FOOTER = "Note: Photo/Video links expire 7 days after report approval.";
async function renderPdf(job, profileCtx, params, reports, statusRows) {
  return renderExportPdf({
    exportType: job.exportType,
    format: job.format,
    params,
    profileCtx,
    reports,
    statusRows,
    mediaExpiryFooter: MEDIA_EXPIRY_FOOTER
  });
}
async function processExportJob(jobId) {
  const adminDb = getAdminDb();
  const result = await adminDb.query({
    exportJobs: { $: { where: { id: jobId } } }
  });
  const job = result.exportJobs?.[0];
  if (!job) throw new Error("Job not found");
  if (job.status === "completed") return job;
  if (job.status === "processing") {
    const started = job.startedAt ? new Date(job.startedAt).getTime() : 0;
    const stale = !started || Date.now() - started > 5 * 60 * 1e3;
    if (!stale) return job;
  }
  const now = (/* @__PURE__ */ new Date()).toISOString();
  await adminDb.transact(
    adminDb.tx.exportJobs[jobId].update({
      status: "processing",
      startedAt: now
    })
  );
  try {
    const profileCtx = await loadProfileContext(job.requesterUserId);
    assertExportJobAccess(profileCtx.role, job.exportType, profileCtx.roleDefinition);
    const params = JSON.parse(job.paramsJson || "{}");
    let content;
    let rowCount = 0;
    let truncated = false;
    let warningHeader = "";
    let reports = [];
    let statusRows = [];
    if (job.format === "csv") {
      if (job.exportType === "dashboard") {
        const gen = await generateDashboardCsv(profileCtx, params);
        content = gen.csv;
        rowCount = gen.rowCount;
        truncated = gen.truncated;
        warningHeader = gen.warningHeader;
        reports = gen.reports;
      } else if (job.exportType === "failure_history") {
        if (job.format !== "csv") {
          throw new Error("Failure history export supports CSV only");
        }
        const gen = await generateFailureHistoryCsv(profileCtx, params);
        content = gen.csv;
        rowCount = gen.rowCount;
        truncated = gen.truncated;
        warningHeader = gen.warningHeader;
        reports = gen.reports;
      } else {
        const gen = await generateReviewStatusCsv(profileCtx, params);
        content = gen.csv;
        rowCount = gen.rowCount;
        truncated = gen.truncated;
        warningHeader = gen.warningHeader;
        statusRows = gen.statusRows;
        reports = gen.reports;
      }
    } else if (job.format === "pdf") {
      if (job.exportType === "dashboard") {
        const gen = await generateDashboardCsv(profileCtx, params);
        reports = gen.reports;
        rowCount = gen.rowCount;
        truncated = gen.truncated;
        warningHeader = gen.warningHeader;
      } else {
        const gen = await generateReviewStatusCsv(profileCtx, params);
        statusRows = gen.statusRows;
        reports = gen.reports;
        rowCount = gen.rowCount;
        truncated = gen.truncated;
        warningHeader = gen.warningHeader;
      }
      content = await renderPdf(job, profileCtx, params, reports, statusRows);
    } else {
      throw new Error(`Unsupported format: ${job.format}`);
    }
    const { filePath, downloadUrl } = await uploadExportFile(jobId, job.format, content);
    const completedAt = (/* @__PURE__ */ new Date()).toISOString();
    await adminDb.transact(
      adminDb.tx.exportJobs[jobId].update({
        status: "completed",
        rowCount,
        truncated,
        warningHeader,
        filePath,
        downloadUrl,
        completedAt,
        errorMessage: ""
      })
    );
    await logExportCompleted(jobId, { rowCount, truncated });
    const updated = await adminDb.query({
      exportJobs: { $: { where: { id: jobId } } }
    });
    return updated.exportJobs?.[0];
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    await adminDb.transact(
      adminDb.tx.exportJobs[jobId].update({
        status: "failed",
        errorMessage: msg,
        completedAt: (/* @__PURE__ */ new Date()).toISOString()
      })
    );
    await logExportFailed(jobId, msg);
    throw e;
  }
}
async function processPendingJobs(limit = 5) {
  const adminDb = getAdminDb();
  const result = await adminDb.query({
    exportJobs: {}
  });
  const staleMs = 5 * 60 * 1e3;
  const now = Date.now();
  const jobs = (result.exportJobs ?? []).filter((job) => {
    if (job.status === "pending") return true;
    if (job.status === "processing") {
      const started = job.startedAt ? new Date(job.startedAt).getTime() : 0;
      return !started || now - started > staleMs;
    }
    return false;
  }).slice(0, limit);
  const outcomes = [];
  for (const job of jobs) {
    try {
      const completed = await processExportJob(job.id);
      outcomes.push({ jobId: job.id, status: completed?.status ?? "completed" });
    } catch (e) {
      outcomes.push({
        jobId: job.id,
        status: "failed",
        error: e instanceof Error ? e.message : String(e)
      });
    }
  }
  return outcomes;
}

// api/_lib/export/routes.js
var INLINE_BUDGET_MS = 5e3;
function triggerBackgroundProcess(jobId, host) {
  const base = host ? `https://${host}` : "";
  if (!base) return;
  fetch(`${base}/api/export?action=process&jobId=${encodeURIComponent(jobId)}`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${process.env.CRON_SECRET ?? ""}`
    }
  }).catch((err) => console.error("[export] background trigger failed", err));
}
async function handleCreate(req, res) {
  const profileCtx = await authenticateExportRequest(req);
  const body = parseBody(req.body) ?? {};
  const exportType = body.exportType;
  const format = body.format === "pdf" ? "pdf" : "csv";
  if (!exportType || !["dashboard", "review_status", "failure_history"].includes(exportType)) {
    return res.status(400).json({ error: "Invalid exportType" });
  }
  assertExportJobAccess(profileCtx.role, exportType, profileCtx.roleDefinition);
  const scopeMeta = exportType === "dashboard" || exportType === "failure_history" ? resolveDashboardScope(profileCtx, body) : resolveReviewStatusScope(profileCtx, body);
  const jobId = id2();
  const now = (/* @__PURE__ */ new Date()).toISOString();
  const adminDb = getAdminDb();
  const paramsJson = JSON.stringify(body);
  await adminDb.transact(
    adminDb.tx.exportJobs[jobId].update({
      requesterUserId: profileCtx.userId,
      exportType,
      format,
      status: "pending",
      paramsJson,
      rowCount: 0,
      truncated: false,
      warningHeader: "",
      filePath: "",
      downloadUrl: "",
      errorMessage: "",
      startedAt: "",
      completedAt: "",
      createdAt: now
    })
  );
  await logExportRequested({
    userId: profileCtx.userId,
    role: profileCtx.role,
    exportType,
    format,
    dateRangeJson: scopeMeta.dateRangeJson,
    storeScopeJson: scopeMeta.storeScopeJson,
    paramsJson,
    jobId
  });
  const start = Date.now();
  let completedInline = false;
  try {
    const job = await processExportJob(jobId);
    if (job?.status === "completed" && Date.now() - start < INLINE_BUDGET_MS) {
      completedInline = true;
      return res.status(200).json({
        jobId,
        status: "completed",
        downloadUrl: job.downloadUrl,
        rowCount: job.rowCount,
        truncated: job.truncated
      });
    }
  } catch {
    await adminDb.transact(
      adminDb.tx.exportJobs[jobId].update({
        status: "pending",
        errorMessage: "",
        startedAt: ""
      })
    );
  }
  if (!completedInline) {
    triggerBackgroundProcess(jobId, req.headers.host);
  }
  return res.status(202).json({ jobId, status: "pending" });
}
async function handleStatus(req, res) {
  const profileCtx = await authenticateExportRequest(req);
  const jobId = req.query.jobId;
  if (!jobId || typeof jobId !== "string") {
    return res.status(400).json({ error: "Missing jobId" });
  }
  const adminDb = getAdminDb();
  const result = await adminDb.query({
    exportJobs: { $: { where: { id: jobId } } }
  });
  const job = result.exportJobs?.[0];
  if (!job) return res.status(404).json({ error: "Job not found" });
  if (job.requesterUserId !== profileCtx.userId) {
    return res.status(403).json({ error: "Forbidden" });
  }
  return res.status(200).json({
    jobId: job.id,
    status: job.status,
    downloadUrl: job.downloadUrl || null,
    rowCount: job.rowCount ?? 0,
    truncated: job.truncated ?? false,
    warningHeader: job.warningHeader ?? "",
    errorMessage: job.errorMessage ?? "",
    format: job.format,
    exportType: job.exportType
  });
}
async function handleAck(req, res) {
  const profileCtx = await authenticateExportRequest(req);
  const body = parseBody(req.body) ?? {};
  const jobId = body.jobId;
  if (!jobId) return res.status(400).json({ error: "Missing jobId" });
  const adminDb = getAdminDb();
  const result = await adminDb.query({
    exportJobs: { $: { where: { id: jobId } } }
  });
  const job = result.exportJobs?.[0];
  if (!job) return res.status(404).json({ error: "Job not found" });
  if (job.requesterUserId !== profileCtx.userId) {
    return res.status(403).json({ error: "Forbidden" });
  }
  await logExportDownloaded(jobId);
  return res.status(200).json({ ok: true });
}
async function handleProcess(req, res) {
  if (!verifyCronSecret(req)) {
    return res.status(401).json({ error: "Unauthorized" });
  }
  const jobId = req.query.jobId;
  if (jobId && typeof jobId === "string") {
    const job = await processExportJob(jobId);
    return res.status(200).json({ processed: 1, outcomes: [{ jobId, status: job?.status }] });
  }
  const outcomes = await processPendingJobs(5);
  return res.status(200).json({ processed: outcomes.length, outcomes });
}
async function handler(req, res) {
  const actionFromQuery = typeof req.query.action === "string" ? req.query.action : "";
  const isCronGet = req.method === "GET" && verifyCronSecret(req) && !req.query.jobId && (!actionFromQuery || actionFromQuery === "process");
  const action = actionFromQuery || (isCronGet ? "process" : req.method === "GET" ? "status" : "create");
  try {
    if (action === "create" && req.method === "POST") {
      return await handleCreate(req, res);
    }
    if (action === "status" && req.method === "GET") {
      return await handleStatus(req, res);
    }
    if (action === "ack" && req.method === "POST") {
      return await handleAck(req, res);
    }
    if (action === "process" && (req.method === "POST" || req.method === "GET")) {
      return await handleProcess(req, res);
    }
    return res.status(405).json({ error: "Method not allowed" });
  } catch (e) {
    console.error("[export]", e);
    const status = e.status ?? 500;
    return res.status(status).json({
      error: e instanceof Error ? e.message : "Export request failed"
    });
  }
}
export {
  handler as default
};
