/* Generated by scripts/bundle-export-api.mjs — do not edit by hand */
"use strict";
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// api/_lib/export/routes.js
var routes_exports = {};
__export(routes_exports, {
  default: () => handler
});
module.exports = __toCommonJS(routes_exports);
var import_admin3 = require("@instantdb/admin");

// api/_lib/export/instant-admin.js
var import_admin = require("@instantdb/admin");
var DEFAULT_APP_ID = "f7ac027e-2079-41eb-8f34-aa0e4543ca71";
function getCredentials() {
  const appId = process.env.VITE_INSTANT_APP_ID || process.env.INSTANT_APP_ID || DEFAULT_APP_ID;
  const adminToken = process.env.INSTANT_ADMIN_TOKEN || process.env.INSTANT_APP_ADMIN_TOKEN || process.env.INSTANT_CLI_AUTH_TOKEN || "";
  if (!adminToken) {
    throw new Error("Missing INSTANT_ADMIN_TOKEN");
  }
  return { appId, adminToken };
}
function getAdminDb() {
  const { appId, adminToken } = getCredentials();
  return (0, import_admin.init)({ appId, adminToken });
}
function parseBody(raw) {
  if (!raw) return null;
  if (typeof raw === "object") return raw;
  if (typeof raw === "string") {
    try {
      return JSON.parse(raw);
    } catch {
      return null;
    }
  }
  return null;
}
function extractBearerToken(req) {
  const authHeader = req.headers["authorization"] || req.headers["token"];
  const raw = Array.isArray(authHeader) ? authHeader[0] : authHeader;
  if (!raw) return null;
  if (raw.startsWith("Bearer ")) return raw.slice(7).trim();
  return raw.trim();
}
function verifyCronSecret(req) {
  const cronSecret = process.env.CRON_SECRET;
  if (!cronSecret) return true;
  const authHeader = req.headers["authorization"];
  const token = Array.isArray(authHeader) ? authHeader[0] : authHeader;
  return token === `Bearer ${cronSecret}`;
}

// api/_lib/export/auth.js
async function verifyRequestUser(req) {
  const token = extractBearerToken(req);
  if (!token) {
    const err = new Error("Missing authorization token");
    err.status = 401;
    throw err;
  }
  const adminDb = getAdminDb();
  const user = await adminDb.auth.verifyToken(token);
  if (!user?.id) {
    const err = new Error("Invalid or expired token");
    err.status = 401;
    throw err;
  }
  return { userId: user.id, email: user.email ?? "" };
}
async function loadProfileContext(userId) {
  const adminDb = getAdminDb();
  const result = await adminDb.query({
    profiles: {
      $: { where: { userId } },
      stores: {}
    }
  });
  const profile = result.profiles?.[0];
  if (!profile) {
    const err = new Error("Profile not found");
    err.status = 403;
    throw err;
  }
  if (profile.approvalStatus !== "approved") {
    const err = new Error("Account not approved");
    err.status = 403;
    throw err;
  }
  const storeIds = (profile.stores ?? []).map((s) => s.id);
  return {
    profileId: profile.id,
    userId: profile.userId,
    role: profile.role,
    approvalStatus: profile.approvalStatus,
    displayName: profile.displayName ?? "",
    email: profile.email ?? "",
    storeIds,
    stores: profile.stores ?? []
  };
}
async function authenticateExportRequest(req) {
  const { userId, email } = await verifyRequestUser(req);
  const ctx = await loadProfileContext(userId);
  return { ...ctx, email };
}

// api/_lib/export/rbac.js
var DASHBOARD_ROLES = /* @__PURE__ */ new Set(["owner", "areaManager"]);
var REVIEW_EXPORT_ROLES = /* @__PURE__ */ new Set(["manager", "leader", "subleader"]);
var DENIED_ROLES = /* @__PURE__ */ new Set(["staff", "viewer"]);
function assertDashboardExportRole(role) {
  if (DENIED_ROLES.has(role) || !DASHBOARD_ROLES.has(role)) {
    const err = new Error("Forbidden: dashboard export requires owner or areaManager role");
    err.status = 403;
    throw err;
  }
}
function assertReviewStatusExportRole(role) {
  if (DENIED_ROLES.has(role) || !REVIEW_EXPORT_ROLES.has(role)) {
    const err = new Error("Forbidden: review status export requires manager, leader, or subleader role");
    err.status = 403;
    throw err;
  }
}
function assertExportJobAccess(role, exportType) {
  if (exportType === "dashboard") {
    assertDashboardExportRole(role);
  } else if (exportType === "review_status") {
    assertReviewStatusExportRole(role);
  } else {
    const err = new Error("Invalid export type");
    err.status = 400;
    throw err;
  }
}

// api/_lib/export/scope.js
var MASTER_ROLES = /* @__PURE__ */ new Set(["owner", "areaManager"]);
function resolveDashboardScope(profileCtx, params) {
  const { role, storeIds: assignedStoreIds } = profileCtx;
  const scope = params.scope === "full_history" ? "full_history" : "filtered";
  const filterStoreId = params.filterStoreId === "all" || !params.filterStoreId ? "all" : params.filterStoreId;
  let allowedStoreIds = null;
  if (MASTER_ROLES.has(role)) {
    if (filterStoreId !== "all") {
      allowedStoreIds = [filterStoreId];
    }
  } else {
    allowedStoreIds = assignedStoreIds;
    if (filterStoreId !== "all" && assignedStoreIds.includes(filterStoreId)) {
      allowedStoreIds = [filterStoreId];
    }
  }
  const dateFilter = scope === "full_history" ? null : {
    startDate: params.startDate,
    endDate: params.endDate
  };
  if (scope === "filtered" && (!params.startDate || !params.endDate)) {
    const err = new Error("startDate and endDate required for filtered scope");
    err.status = 400;
    throw err;
  }
  return {
    scope,
    allowedStoreIds,
    dateFilter,
    filterStoreId,
    storeScopeJson: JSON.stringify({
      allowedStoreIds,
      filterStoreId,
      scope
    }),
    dateRangeJson: JSON.stringify(
      dateFilter ?? { startDate: null, endDate: null, allTime: true }
    )
  };
}
function resolveReviewStatusScope(profileCtx, params) {
  const { storeIds: assignedStoreIds } = profileCtx;
  if (!assignedStoreIds.length) {
    const err = new Error("No stores assigned to this user");
    err.status = 403;
    throw err;
  }
  const scope = params.scope === "all_assigned" ? "all_assigned" : "current_list";
  const daysBack = Number(params.daysBack) > 0 ? Number(params.daysBack) : 30;
  const limit = scope === "current_list" ? Number(params.limit) > 0 ? Number(params.limit) : 200 : null;
  return {
    scope,
    allowedStoreIds: assignedStoreIds,
    daysBack: scope === "current_list" ? daysBack : null,
    limit,
    storeScopeJson: JSON.stringify({ allowedStoreIds: assignedStoreIds }),
    dateRangeJson: JSON.stringify(
      scope === "current_list" ? { daysBack, limit } : { allTime: true }
    )
  };
}
function filterReportsByStore(reports, allowedStoreIds) {
  if (!allowedStoreIds) return reports;
  const set = new Set(allowedStoreIds);
  return reports.filter((r) => set.has(r.storeId));
}

// api/_lib/export/audit.js
var import_admin2 = require("@instantdb/admin");
async function logExportRequested({
  userId,
  role,
  exportType,
  format,
  dateRangeJson,
  storeScopeJson,
  paramsJson,
  jobId
}) {
  const adminDb = getAdminDb();
  const logId = (0, import_admin2.id)();
  const now = (/* @__PURE__ */ new Date()).toISOString();
  await adminDb.transact(
    adminDb.tx.exportAuditLogs[logId].update({
      userId,
      role,
      exportType,
      format,
      dateRangeJson: dateRangeJson ?? "{}",
      storeScopeJson: storeScopeJson ?? "{}",
      paramsJson: paramsJson ?? "{}",
      rowCount: 0,
      truncated: false,
      jobId,
      status: "requested",
      downloadAt: "",
      createdAt: now
    })
  );
  return logId;
}
async function logExportCompleted(jobId, { rowCount, truncated }) {
  const adminDb = getAdminDb();
  const result = await adminDb.query({
    exportAuditLogs: { $: { where: { jobId, status: "requested" } } }
  });
  const log = result.exportAuditLogs?.[0];
  if (!log) return;
  await adminDb.transact(
    adminDb.tx.exportAuditLogs[log.id].update({
      status: "completed",
      rowCount: rowCount ?? 0,
      truncated: truncated ?? false
    })
  );
}
async function logExportFailed(jobId, errorMessage) {
  const adminDb = getAdminDb();
  const result = await adminDb.query({
    exportAuditLogs: { $: { where: { jobId, status: "requested" } } }
  });
  const log = result.exportAuditLogs?.[0];
  if (!log) return;
  await adminDb.transact(
    adminDb.tx.exportAuditLogs[log.id].update({
      status: "failed",
      paramsJson: JSON.stringify({ error: errorMessage })
    })
  );
}
async function logExportDownloaded(jobId) {
  const adminDb = getAdminDb();
  const result = await adminDb.query({
    exportAuditLogs: { $: { where: { jobId } } }
  });
  const log = result.exportAuditLogs?.[0];
  if (!log) return;
  await adminDb.transact(
    adminDb.tx.exportAuditLogs[log.id].update({
      status: "downloaded",
      downloadAt: (/* @__PURE__ */ new Date()).toISOString()
    })
  );
}

// api/_lib/export/csv-builder.js
var ROW_CAP = 1e5;
var TRUNCATION_WARNING = "# WARNING: Results truncated at 100,000 rows";
function escapeCell(value) {
  if (value == null) return "";
  const str = String(value);
  if (str.includes('"') || str.includes(",") || str.includes("\n") || str.includes("\r")) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}
function buildCsv(headers, rows, options = {}) {
  const { emptyMessage = "# No data for selected scope" } = options;
  const truncated = rows.length > ROW_CAP;
  const dataRows = truncated ? rows.slice(0, ROW_CAP) : rows;
  const lines = [];
  if (truncated) {
    lines.push(TRUNCATION_WARNING);
  }
  if (dataRows.length === 0) {
    lines.push(emptyMessage);
  }
  lines.push(headers.map(escapeCell).join(","));
  for (const row of dataRows) {
    lines.push(headers.map((h) => escapeCell(row[h])).join(","));
  }
  const csv = "\uFEFF" + lines.join("\r\n");
  return {
    csv,
    rowCount: dataRows.length,
    truncated,
    warningHeader: truncated ? TRUNCATION_WARNING : ""
  };
}

// api/_lib/export/queries.js
async function fetchReportsWithResponses(allowedStoreIds, dateFilter) {
  const adminDb = getAdminDb();
  const query = {
    reports: {
      responses: {}
    }
  };
  if (dateFilter?.startDate && dateFilter?.endDate) {
    query.reports.$ = {
      where: {
        reportDate: { $gte: dateFilter.startDate, $lte: dateFilter.endDate }
      }
    };
  }
  const result = await adminDb.query(query);
  let reports = result.reports ?? [];
  reports = filterReportsByStore(reports, allowedStoreIds);
  if (!dateFilter && allowedStoreIds?.length) {
    reports = filterReportsByStore(reports, allowedStoreIds);
  } else if (!dateFilter) {
    reports = filterReportsByStore(reports, null);
  }
  return reports;
}
async function fetchReviewStatusData(allowedStoreIds) {
  const adminDb = getAdminDb();
  const result = await adminDb.query({
    reports: { responses: {} },
    reviewEvents: {},
    profiles: {}
  });
  const reports = filterReportsByStore(result.reports ?? [], allowedStoreIds);
  return {
    reports,
    reviewEvents: result.reviewEvents ?? [],
    profiles: result.profiles ?? []
  };
}
async function fetchMediaByResponseIds(responseIds) {
  if (!responseIds.length) return {};
  const adminDb = getAdminDb();
  const result = await adminDb.query({
    mediaRecords: {}
  });
  const map = {};
  for (const m of result.mediaRecords ?? []) {
    if (!responseIds.includes(m.reportResponseId)) continue;
    if (!map[m.reportResponseId]) map[m.reportResponseId] = [];
    map[m.reportResponseId].push(m);
  }
  return map;
}

// api/_lib/export/row-mappers.js
function mediaStorageDeleted(mediaList) {
  if (!mediaList?.length) return false;
  return mediaList.every((m) => m.storageDeleted === true);
}
function mapDashboardRows(reports, mediaByResponseId = {}) {
  const rows = [];
  for (const report of reports) {
    const responses = report.responses ?? [];
    if (!responses.length) {
      rows.push({
        report_id: report.id,
        report_date: report.reportDate,
        store_code: report.storeCode,
        store_name: report.storeName,
        template_name: report.templateName,
        report_status: report.status,
        completion_percent: report.completionPercent ?? 0,
        compliance_percent: report.compliancePercent ?? 0,
        item_section: "",
        item_title: "",
        item_status: "",
        feedback_code: "",
        feedback_note: "",
        approved_at: "",
        media_storage_deleted: "",
        submitted_by_role: report.submittedByRole ?? ""
      });
      continue;
    }
    for (const resp of responses) {
      const media = mediaByResponseId[resp.id] ?? [];
      rows.push({
        report_id: report.id,
        report_date: report.reportDate,
        store_code: report.storeCode,
        store_name: report.storeName,
        template_name: report.templateName,
        report_status: report.status,
        completion_percent: report.completionPercent ?? 0,
        compliance_percent: report.compliancePercent ?? 0,
        item_section: resp.section ?? "",
        item_title: resp.title ?? "",
        item_status: resp.status ?? "",
        feedback_code: resp.feedbackCode ?? "",
        feedback_note: resp.feedbackNote || resp.rejectionReason || "",
        approved_at: resp.approvedAt ?? "",
        media_storage_deleted: media.length ? mediaStorageDeleted(media) : "",
        submitted_by_role: report.submittedByRole ?? ""
      });
    }
  }
  return rows;
}
var DASHBOARD_CSV_HEADERS = [
  "report_id",
  "report_date",
  "store_code",
  "store_name",
  "template_name",
  "report_status",
  "completion_percent",
  "compliance_percent",
  "item_section",
  "item_title",
  "item_status",
  "feedback_code",
  "feedback_note",
  "approved_at",
  "media_storage_deleted",
  "submitted_by_role"
];
function mapReviewStatusRows(statusRows) {
  return statusRows.map((row) => ({
    report_date: row.reportDate,
    store_code: row.storeCode,
    submitted_by: row.submittedBy,
    submitted_time: row.submittedTime,
    status: row.status,
    latest_review_time: row.latestReviewTime,
    latest_feedback: row.latestFeedback,
    finalized_time: row.finalizedTime,
    lead_time_ms: row.leadTimeMs ?? "",
    correction_duration_ms: row.correctionDurationMs ?? ""
  }));
}
var REVIEW_STATUS_CSV_HEADERS = [
  "report_date",
  "store_code",
  "submitted_by",
  "submitted_time",
  "status",
  "latest_review_time",
  "latest_feedback",
  "finalized_time",
  "lead_time_ms",
  "correction_duration_ms"
];

// api/_lib/export/generators/dashboard-csv.js
async function generateDashboardCsv(profileCtx, params) {
  const scopeResult = resolveDashboardScope(profileCtx, params);
  const { allowedStoreIds, dateFilter } = scopeResult;
  const reports = await fetchReportsWithResponses(allowedStoreIds, dateFilter);
  const responseIds = [];
  for (const r of reports) {
    for (const resp of r.responses ?? []) {
      responseIds.push(resp.id);
    }
  }
  const mediaByResponseId = await fetchMediaByResponseIds(responseIds);
  const rows = mapDashboardRows(reports, mediaByResponseId);
  const result = buildCsv(DASHBOARD_CSV_HEADERS, rows);
  return {
    ...result,
    scopeResult,
    reports
  };
}

// api/_lib/export/review-status-rows.js
var STATUS_ORDER = {
  waiting_approval: 0,
  need_correction: 1,
  rejected: 2,
  approved: 3
};
function parseMs(iso) {
  if (!iso?.trim()) return null;
  const ms = new Date(iso).getTime();
  return Number.isNaN(ms) ? null : ms;
}
function formatDisplay(iso) {
  if (!iso?.trim()) return "\u2014";
  try {
    return new Date(iso).toLocaleString("en-GB", {
      day: "2-digit",
      month: "short",
      year: "numeric",
      hour: "2-digit",
      minute: "2-digit"
    });
  } catch {
    return iso;
  }
}
function resolveSubmitterName(report, profiles) {
  const profile = profiles.find((p) => p.userId === report.submittedByUserId);
  if (profile?.displayName?.trim()) return profile.displayName.trim();
  if (profile?.email) return profile.email.split("@")[0] ?? profile.email;
  return report.submittedByRole || "\u2014";
}
function latestReviewIso(report, events) {
  const responses = report.responses ?? [];
  const responseTimes = responses.map((r) => r.approvedAt).filter((t) => t?.trim());
  const reviewEventTypes = /* @__PURE__ */ new Set([
    "item_approved",
    "item_rejected",
    "item_correction",
    "report_finalized"
  ]);
  const eventTimes = events.filter((e) => e.reportId === report.id && reviewEventTypes.has(e.eventType)).map((e) => e.createdAt);
  const all = [...responseTimes, ...eventTimes].sort((a, b) => b.localeCompare(a));
  return all[0] ?? null;
}
function latestFeedbackNote(report, events) {
  const responses = report.responses ?? [];
  const flagged = responses.filter(
    (r) => ["rejected", "need_correction"].includes(r.status) && r.rejectionReason?.trim()
  );
  if (flagged.length) {
    const sorted = [...flagged].sort(
      (a, b) => (b.updatedAt || b.approvedAt || "").localeCompare(a.updatedAt || a.approvedAt || "")
    );
    return sorted[0].rejectionReason.trim();
  }
  const feedbackEvents = events.filter(
    (e) => e.reportId === report.id && (e.eventType === "item_correction" || e.eventType === "item_rejected") && e.note?.trim()
  ).sort((a, b) => b.createdAt.localeCompare(a.createdAt));
  return feedbackEvents[0]?.note?.trim() ?? "";
}
function computeCorrectionDurationMs(events, reportId) {
  const reportEvents = events.filter((e) => e.reportId === reportId).sort((a, b) => a.createdAt.localeCompare(b.createdAt));
  let maxGap = null;
  for (let i = 0; i < reportEvents.length; i++) {
    const ev = reportEvents[i];
    if (ev.eventType !== "item_correction" && ev.eventType !== "item_rejected") continue;
    const correctionMs = parseMs(ev.createdAt);
    if (correctionMs == null) continue;
    const resubmit = reportEvents.slice(i + 1).find((e) => e.eventType === "resubmitted" && e.createdAt > ev.createdAt);
    if (!resubmit) continue;
    const resubmitMs = parseMs(resubmit.createdAt);
    if (resubmitMs == null) continue;
    const gap = resubmitMs - correctionMs;
    if (gap >= 0 && (maxGap == null || gap > maxGap)) {
      maxGap = gap;
    }
  }
  return maxGap;
}
function isWithinDateWindow(reportDate, daysBack) {
  if (!reportDate?.trim()) return false;
  const end = /* @__PURE__ */ new Date();
  const start = /* @__PURE__ */ new Date();
  start.setDate(start.getDate() - daysBack);
  const startStr = start.toISOString().slice(0, 10);
  const endStr = end.toISOString().slice(0, 10);
  return reportDate >= startStr && reportDate <= endStr;
}
function sortReports(a, b) {
  const orderA = STATUS_ORDER[a.status] ?? 99;
  const orderB = STATUS_ORDER[b.status] ?? 99;
  if (orderA !== orderB) return orderA - orderB;
  return (b.submittedAt ?? "").localeCompare(a.submittedAt ?? "");
}
function buildReportTimeline(report, events) {
  const reportEvents = events.filter((e) => e.reportId === report.id);
  const finalized = [...reportEvents].reverse().find((e) => e.eventType === "report_finalized");
  const firstSubmitted = reportEvents.find((e) => e.eventType === "submitted") ?? (report.submittedAt ? { createdAt: report.submittedAt } : null);
  const firstMs = firstSubmitted ? parseMs(firstSubmitted.createdAt) : null;
  const endMs = finalized ? parseMs(finalized.createdAt) : null;
  const totalDurationMs = firstMs != null && endMs != null ? endMs - firstMs : null;
  return {
    finalizedAt: finalized?.createdAt ?? null,
    totalDurationMs,
    source: reportEvents.length > 0 ? "events" : "inferred"
  };
}
function buildReviewStatusRows(reports, profiles, events, options) {
  const { daysBack = 30, limit = 200, scope = "current_list" } = options;
  let filtered = [...reports];
  if (scope === "current_list") {
    filtered = filtered.filter((r) => isWithinDateWindow(r.reportDate, daysBack)).sort(sortReports).slice(0, limit);
  }
  return filtered.map((report) => {
    const reportEvents = events.filter((e) => e.reportId === report.id);
    const timeline = buildReportTimeline(report, reportEvents);
    const latestReview = latestReviewIso(report, reportEvents);
    return {
      report,
      reportDate: report.reportDate,
      storeCode: report.storeCode,
      submittedBy: resolveSubmitterName(report, profiles),
      submittedTime: formatDisplay(report.submittedAt),
      status: report.status,
      latestReviewTime: formatDisplay(latestReview ?? void 0),
      latestFeedback: latestFeedbackNote(report, reportEvents),
      finalizedTime: timeline.finalizedAt ? formatDisplay(timeline.finalizedAt) : "\u2014",
      leadTimeMs: timeline.totalDurationMs,
      correctionDurationMs: computeCorrectionDurationMs(events, report.id),
      timelineSource: timeline.source
    };
  });
}
function computeDashboardKpis(reports) {
  if (!reports.length) {
    return {
      reportCount: 0,
      avgCompletion: 0,
      avgCompliance: 0,
      failedItemCount: 0
    };
  }
  const completion = Math.round(
    reports.reduce((sum, r) => sum + (r.completionPercent ?? 0), 0) / reports.length
  );
  const compliance = Math.round(
    reports.reduce((sum, r) => sum + (r.compliancePercent ?? 0), 0) / reports.length
  );
  const failSet = /* @__PURE__ */ new Set();
  for (const report of reports) {
    for (const resp of report.responses ?? []) {
      if (resp.status === "rejected") failSet.add(resp.title);
    }
  }
  return {
    reportCount: reports.length,
    avgCompletion: completion,
    avgCompliance: compliance,
    failedItemCount: failSet.size
  };
}

// api/_lib/export/generators/review-status-csv.js
async function generateReviewStatusCsv(profileCtx, params) {
  const scopeResult = resolveReviewStatusScope(profileCtx, params);
  const { allowedStoreIds, daysBack, limit, scope } = scopeResult;
  const { reports, reviewEvents, profiles } = await fetchReviewStatusData(allowedStoreIds);
  const statusRows = buildReviewStatusRows(reports, profiles, reviewEvents, {
    daysBack: daysBack ?? 30,
    limit: limit ?? 200,
    scope
  });
  const rows = mapReviewStatusRows(statusRows);
  const result = buildCsv(REVIEW_STATUS_CSV_HEADERS, rows);
  return {
    ...result,
    scopeResult,
    statusRows,
    reports
  };
}

// api/_lib/export/storage.js
async function uploadExportFile(jobId, format, content) {
  const adminDb = getAdminDb();
  const ext = format === "pdf" ? "pdf" : "csv";
  const path = `exports/${jobId}.${ext}`;
  const contentType = format === "pdf" ? "application/pdf" : "text/csv; charset=utf-8";
  const buffer = Buffer.isBuffer(content) ? content : Buffer.from(content, format === "pdf" ? void 0 : "utf8");
  const { data: fileData } = await adminDb.storage.uploadFile(path, buffer, {
    contentType
  });
  if (!fileData?.id) throw new Error("Export upload returned no file ID");
  const filesResult = await adminDb.query({
    $files: { $: { where: { id: fileData.id } } }
  });
  const downloadUrl = filesResult?.$files?.[0]?.url ?? "";
  return { filePath: path, downloadUrl, fileId: fileData.id };
}

// api/_lib/export/pdf/render-pdf.js
var import_react3 = __toESM(require("react"), 1);
var import_renderer3 = require("@react-pdf/renderer");

// api/_lib/export/pdf/DashboardPdfDocument.js
var import_react = __toESM(require("react"), 1);
var import_renderer = require("@react-pdf/renderer");
var styles = import_renderer.StyleSheet.create({
  page: { padding: 32, fontSize: 9, fontFamily: "Helvetica" },
  title: { fontSize: 16, marginBottom: 8, fontFamily: "Helvetica-Bold" },
  subtitle: { fontSize: 10, marginBottom: 16, color: "#444" },
  kpiRow: { flexDirection: "row", marginBottom: 16, gap: 12 },
  kpiBox: { flex: 1, padding: 8, backgroundColor: "#f5f5f5", borderRadius: 4 },
  kpiLabel: { fontSize: 8, color: "#666" },
  kpiValue: { fontSize: 14, fontFamily: "Helvetica-Bold", marginTop: 2 },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#333",
    color: "#fff",
    padding: 4,
    fontFamily: "Helvetica-Bold",
    fontSize: 7
  },
  tableRow: { flexDirection: "row", borderBottomWidth: 0.5, borderColor: "#ddd", padding: 3, fontSize: 7 },
  colDate: { width: "12%" },
  colStore: { width: "10%" },
  colTemplate: { width: "18%" },
  colStatus: { width: "12%" },
  colPct: { width: "10%" },
  colItem: { width: "20%" },
  colItemStatus: { width: "18%" },
  footer: { position: "absolute", bottom: 24, left: 32, right: 32, fontSize: 7, color: "#c00" },
  warning: { backgroundColor: "#fff3cd", padding: 8, marginBottom: 12, fontSize: 8, color: "#856404" }
});
function formatScopeLabel(params) {
  if (params.scope === "full_history") return "Full accessible history";
  return `${params.startDate ?? ""} \u2014 ${params.endDate ?? ""}`;
}
function DashboardPdfDocument({ params, reports, kpis, mediaExpiryFooter }) {
  const rows = [];
  for (const report of reports.slice(0, 500)) {
    const responses = report.responses ?? [];
    if (!responses.length) {
      rows.push({ report, resp: null });
    } else {
      for (const resp of responses.slice(0, 20)) {
        rows.push({ report, resp });
      }
    }
  }
  return import_react.default.createElement(
    import_renderer.Document,
    null,
    import_react.default.createElement(
      import_renderer.Page,
      { size: "A4", style: styles.page },
      import_react.default.createElement(import_renderer.Text, { style: styles.title }, "Operation Dashboard Export"),
      import_react.default.createElement(import_renderer.Text, { style: styles.subtitle }, `Period: ${formatScopeLabel(params)}`),
      import_react.default.createElement(
        import_renderer.View,
        { style: styles.warning },
        import_react.default.createElement(import_renderer.Text, null, mediaExpiryFooter)
      ),
      import_react.default.createElement(
        import_renderer.View,
        { style: styles.kpiRow },
        import_react.default.createElement(
          import_renderer.View,
          { style: styles.kpiBox },
          import_react.default.createElement(import_renderer.Text, { style: styles.kpiLabel }, "Total Reports"),
          import_react.default.createElement(import_renderer.Text, { style: styles.kpiValue }, String(kpis.reportCount))
        ),
        import_react.default.createElement(
          import_renderer.View,
          { style: styles.kpiBox },
          import_react.default.createElement(import_renderer.Text, { style: styles.kpiLabel }, "Avg Completion"),
          import_react.default.createElement(import_renderer.Text, { style: styles.kpiValue }, `${kpis.avgCompletion}%`)
        ),
        import_react.default.createElement(
          import_renderer.View,
          { style: styles.kpiBox },
          import_react.default.createElement(import_renderer.Text, { style: styles.kpiLabel }, "Avg Compliance"),
          import_react.default.createElement(import_renderer.Text, { style: styles.kpiValue }, `${kpis.avgCompliance}%`)
        ),
        import_react.default.createElement(
          import_renderer.View,
          { style: styles.kpiBox },
          import_react.default.createElement(import_renderer.Text, { style: styles.kpiLabel }, "Failed Items"),
          import_react.default.createElement(import_renderer.Text, { style: styles.kpiValue }, String(kpis.failedItemCount))
        )
      ),
      import_react.default.createElement(
        import_renderer.View,
        { style: styles.tableHeader },
        import_react.default.createElement(import_renderer.Text, { style: styles.colDate }, "Date"),
        import_react.default.createElement(import_renderer.Text, { style: styles.colStore }, "Store"),
        import_react.default.createElement(import_renderer.Text, { style: styles.colTemplate }, "Template"),
        import_react.default.createElement(import_renderer.Text, { style: styles.colStatus }, "Status"),
        import_react.default.createElement(import_renderer.Text, { style: styles.colPct }, "Complete"),
        import_react.default.createElement(import_renderer.Text, { style: styles.colItem }, "Item"),
        import_react.default.createElement(import_renderer.Text, { style: styles.colItemStatus }, "Item Status")
      ),
      ...rows.map(
        ({ report, resp }, i) => import_react.default.createElement(
          import_renderer.View,
          { key: i, style: styles.tableRow },
          import_react.default.createElement(import_renderer.Text, { style: styles.colDate }, report.reportDate),
          import_react.default.createElement(import_renderer.Text, { style: styles.colStore }, report.storeCode),
          import_react.default.createElement(import_renderer.Text, { style: styles.colTemplate }, report.templateName),
          import_react.default.createElement(import_renderer.Text, { style: styles.colStatus }, report.status),
          import_react.default.createElement(import_renderer.Text, { style: styles.colPct }, `${report.completionPercent ?? 0}%`),
          import_react.default.createElement(import_renderer.Text, { style: styles.colItem }, resp?.title ?? "\u2014"),
          import_react.default.createElement(import_renderer.Text, { style: styles.colItemStatus }, resp?.status ?? "\u2014")
        )
      ),
      import_react.default.createElement(import_renderer.Text, { style: styles.footer, fixed: true }, mediaExpiryFooter)
    )
  );
}

// api/_lib/export/pdf/ReviewStatusPdfDocument.js
var import_react2 = __toESM(require("react"), 1);
var import_renderer2 = require("@react-pdf/renderer");
var styles2 = import_renderer2.StyleSheet.create({
  page: { padding: 32, fontSize: 9, fontFamily: "Helvetica" },
  title: { fontSize: 16, marginBottom: 8, fontFamily: "Helvetica-Bold" },
  subtitle: { fontSize: 10, marginBottom: 16, color: "#444" },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#333",
    color: "#fff",
    padding: 4,
    fontFamily: "Helvetica-Bold",
    fontSize: 7
  },
  tableRow: { flexDirection: "row", borderBottomWidth: 0.5, borderColor: "#ddd", padding: 3, fontSize: 7 },
  colDate: { width: "10%" },
  colStore: { width: "8%" },
  colSubmitter: { width: "12%" },
  colStatus: { width: "10%" },
  colReview: { width: "12%" },
  colFeedback: { width: "18%" },
  colFinal: { width: "12%" },
  colLead: { width: "10%" },
  colCorrection: { width: "8%" },
  footer: { position: "absolute", bottom: 24, left: 32, right: 32, fontSize: 7, color: "#c00" },
  warning: { backgroundColor: "#fff3cd", padding: 8, marginBottom: 12, fontSize: 8, color: "#856404" }
});
function formatScopeLabel2(params) {
  if (params.scope === "all_assigned") return "All assigned reports";
  return `Last ${params.daysBack ?? 30} days`;
}
function formatMs(ms) {
  if (ms == null) return "\u2014";
  const totalMinutes = Math.floor(ms / 6e4);
  const hours = Math.floor(totalMinutes / 60);
  const minutes = totalMinutes % 60;
  if (hours > 0) return `${hours}h ${minutes}m`;
  if (minutes > 0) return `${minutes}m`;
  return "<1m";
}
function ReviewStatusPdfDocument({ params, statusRows, mediaExpiryFooter }) {
  return import_react2.default.createElement(
    import_renderer2.Document,
    null,
    import_react2.default.createElement(
      import_renderer2.Page,
      { size: "A4", orientation: "landscape", style: styles2.page },
      import_react2.default.createElement(import_renderer2.Text, { style: styles2.title }, "Report Review Status Export"),
      import_react2.default.createElement(import_renderer2.Text, { style: styles2.subtitle }, formatScopeLabel2(params)),
      import_react2.default.createElement(
        import_renderer2.View,
        { style: styles2.warning },
        import_react2.default.createElement(import_renderer2.Text, null, mediaExpiryFooter)
      ),
      import_react2.default.createElement(
        import_renderer2.View,
        { style: styles2.tableHeader },
        import_react2.default.createElement(import_renderer2.Text, { style: styles2.colDate }, "Date"),
        import_react2.default.createElement(import_renderer2.Text, { style: styles2.colStore }, "Store"),
        import_react2.default.createElement(import_renderer2.Text, { style: styles2.colSubmitter }, "Submitted By"),
        import_react2.default.createElement(import_renderer2.Text, { style: styles2.colStatus }, "Status"),
        import_react2.default.createElement(import_renderer2.Text, { style: styles2.colReview }, "Latest Review"),
        import_react2.default.createElement(import_renderer2.Text, { style: styles2.colFeedback }, "Feedback"),
        import_react2.default.createElement(import_renderer2.Text, { style: styles2.colFinal }, "Finalized"),
        import_react2.default.createElement(import_renderer2.Text, { style: styles2.colLead }, "Lead Time"),
        import_react2.default.createElement(import_renderer2.Text, { style: styles2.colCorrection }, "Correction")
      ),
      ...statusRows.slice(0, 500).map(
        (row, i) => import_react2.default.createElement(
          import_renderer2.View,
          { key: i, style: styles2.tableRow },
          import_react2.default.createElement(import_renderer2.Text, { style: styles2.colDate }, row.reportDate),
          import_react2.default.createElement(import_renderer2.Text, { style: styles2.colStore }, row.storeCode),
          import_react2.default.createElement(import_renderer2.Text, { style: styles2.colSubmitter }, row.submittedBy),
          import_react2.default.createElement(import_renderer2.Text, { style: styles2.colStatus }, row.status),
          import_react2.default.createElement(import_renderer2.Text, { style: styles2.colReview }, row.latestReviewTime),
          import_react2.default.createElement(import_renderer2.Text, { style: styles2.colFeedback }, row.latestFeedback || "\u2014"),
          import_react2.default.createElement(import_renderer2.Text, { style: styles2.colFinal }, row.finalizedTime),
          import_react2.default.createElement(import_renderer2.Text, { style: styles2.colLead }, formatMs(row.leadTimeMs)),
          import_react2.default.createElement(import_renderer2.Text, { style: styles2.colCorrection }, formatMs(row.correctionDurationMs))
        )
      ),
      import_react2.default.createElement(import_renderer2.Text, { style: styles2.footer, fixed: true }, mediaExpiryFooter)
    )
  );
}

// api/_lib/export/pdf/render-pdf.js
async function renderExportPdf({
  exportType,
  params,
  reports,
  statusRows,
  mediaExpiryFooter
}) {
  let doc;
  if (exportType === "dashboard") {
    const kpis = computeDashboardKpis(reports);
    doc = import_react3.default.createElement(DashboardPdfDocument, {
      params,
      reports,
      kpis,
      mediaExpiryFooter
    });
  } else {
    doc = import_react3.default.createElement(ReviewStatusPdfDocument, {
      params,
      statusRows,
      mediaExpiryFooter
    });
  }
  return (0, import_renderer3.renderToBuffer)(doc);
}

// api/_lib/export/job-runner.js
var MEDIA_EXPIRY_FOOTER = "Note: Photo/Video links expire 7 days after report approval.";
async function renderPdf(job, profileCtx, params, reports, statusRows) {
  return renderExportPdf({
    exportType: job.exportType,
    format: job.format,
    params,
    profileCtx,
    reports,
    statusRows,
    mediaExpiryFooter: MEDIA_EXPIRY_FOOTER
  });
}
async function processExportJob(jobId) {
  const adminDb = getAdminDb();
  const result = await adminDb.query({
    exportJobs: { $: { where: { id: jobId } } }
  });
  const job = result.exportJobs?.[0];
  if (!job) throw new Error("Job not found");
  if (job.status === "completed") return job;
  if (job.status === "processing") {
    const started = job.startedAt ? new Date(job.startedAt).getTime() : 0;
    const stale = !started || Date.now() - started > 5 * 60 * 1e3;
    if (!stale) return job;
  }
  const now = (/* @__PURE__ */ new Date()).toISOString();
  await adminDb.transact(
    adminDb.tx.exportJobs[jobId].update({
      status: "processing",
      startedAt: now
    })
  );
  try {
    const profileCtx = await loadProfileContext(job.requesterUserId);
    assertExportJobAccess(profileCtx.role, job.exportType);
    const params = JSON.parse(job.paramsJson || "{}");
    let content;
    let rowCount = 0;
    let truncated = false;
    let warningHeader = "";
    let reports = [];
    let statusRows = [];
    if (job.format === "csv") {
      if (job.exportType === "dashboard") {
        const gen = await generateDashboardCsv(profileCtx, params);
        content = gen.csv;
        rowCount = gen.rowCount;
        truncated = gen.truncated;
        warningHeader = gen.warningHeader;
        reports = gen.reports;
      } else {
        const gen = await generateReviewStatusCsv(profileCtx, params);
        content = gen.csv;
        rowCount = gen.rowCount;
        truncated = gen.truncated;
        warningHeader = gen.warningHeader;
        statusRows = gen.statusRows;
        reports = gen.reports;
      }
    } else if (job.format === "pdf") {
      if (job.exportType === "dashboard") {
        const gen = await generateDashboardCsv(profileCtx, params);
        reports = gen.reports;
        rowCount = gen.rowCount;
        truncated = gen.truncated;
        warningHeader = gen.warningHeader;
      } else {
        const gen = await generateReviewStatusCsv(profileCtx, params);
        statusRows = gen.statusRows;
        reports = gen.reports;
        rowCount = gen.rowCount;
        truncated = gen.truncated;
        warningHeader = gen.warningHeader;
      }
      content = await renderPdf(job, profileCtx, params, reports, statusRows);
    } else {
      throw new Error(`Unsupported format: ${job.format}`);
    }
    const { filePath, downloadUrl } = await uploadExportFile(jobId, job.format, content);
    const completedAt = (/* @__PURE__ */ new Date()).toISOString();
    await adminDb.transact(
      adminDb.tx.exportJobs[jobId].update({
        status: "completed",
        rowCount,
        truncated,
        warningHeader,
        filePath,
        downloadUrl,
        completedAt,
        errorMessage: ""
      })
    );
    await logExportCompleted(jobId, { rowCount, truncated });
    const updated = await adminDb.query({
      exportJobs: { $: { where: { id: jobId } } }
    });
    return updated.exportJobs?.[0];
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    await adminDb.transact(
      adminDb.tx.exportJobs[jobId].update({
        status: "failed",
        errorMessage: msg,
        completedAt: (/* @__PURE__ */ new Date()).toISOString()
      })
    );
    await logExportFailed(jobId, msg);
    throw e;
  }
}
async function processPendingJobs(limit = 5) {
  const adminDb = getAdminDb();
  const result = await adminDb.query({
    exportJobs: {}
  });
  const staleMs = 5 * 60 * 1e3;
  const now = Date.now();
  const jobs = (result.exportJobs ?? []).filter((job) => {
    if (job.status === "pending") return true;
    if (job.status === "processing") {
      const started = job.startedAt ? new Date(job.startedAt).getTime() : 0;
      return !started || now - started > staleMs;
    }
    return false;
  }).slice(0, limit);
  const outcomes = [];
  for (const job of jobs) {
    try {
      const completed = await processExportJob(job.id);
      outcomes.push({ jobId: job.id, status: completed?.status ?? "completed" });
    } catch (e) {
      outcomes.push({
        jobId: job.id,
        status: "failed",
        error: e instanceof Error ? e.message : String(e)
      });
    }
  }
  return outcomes;
}

// api/_lib/export/routes.js
var INLINE_BUDGET_MS = 5e3;
function triggerBackgroundProcess(jobId, host) {
  const base = host ? `https://${host}` : "";
  if (!base) return;
  fetch(`${base}/api/export?action=process&jobId=${encodeURIComponent(jobId)}`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${process.env.CRON_SECRET ?? ""}`
    }
  }).catch((err) => console.error("[export] background trigger failed", err));
}
async function handleCreate(req, res) {
  const profileCtx = await authenticateExportRequest(req);
  const body = parseBody(req.body) ?? {};
  const exportType = body.exportType;
  const format = body.format === "pdf" ? "pdf" : "csv";
  if (!exportType || !["dashboard", "review_status"].includes(exportType)) {
    return res.status(400).json({ error: "Invalid exportType" });
  }
  assertExportJobAccess(profileCtx.role, exportType);
  const scopeMeta = exportType === "dashboard" ? resolveDashboardScope(profileCtx, body) : resolveReviewStatusScope(profileCtx, body);
  const jobId = (0, import_admin3.id)();
  const now = (/* @__PURE__ */ new Date()).toISOString();
  const adminDb = getAdminDb();
  const paramsJson = JSON.stringify(body);
  await adminDb.transact(
    adminDb.tx.exportJobs[jobId].update({
      requesterUserId: profileCtx.userId,
      exportType,
      format,
      status: "pending",
      paramsJson,
      rowCount: 0,
      truncated: false,
      warningHeader: "",
      filePath: "",
      downloadUrl: "",
      errorMessage: "",
      startedAt: "",
      completedAt: "",
      createdAt: now
    })
  );
  await logExportRequested({
    userId: profileCtx.userId,
    role: profileCtx.role,
    exportType,
    format,
    dateRangeJson: scopeMeta.dateRangeJson,
    storeScopeJson: scopeMeta.storeScopeJson,
    paramsJson,
    jobId
  });
  const start = Date.now();
  let completedInline = false;
  try {
    const job = await processExportJob(jobId);
    if (job?.status === "completed" && Date.now() - start < INLINE_BUDGET_MS) {
      completedInline = true;
      return res.status(200).json({
        jobId,
        status: "completed",
        downloadUrl: job.downloadUrl,
        rowCount: job.rowCount,
        truncated: job.truncated
      });
    }
  } catch {
    await adminDb.transact(
      adminDb.tx.exportJobs[jobId].update({
        status: "pending",
        errorMessage: "",
        startedAt: ""
      })
    );
  }
  if (!completedInline) {
    triggerBackgroundProcess(jobId, req.headers.host);
  }
  return res.status(202).json({ jobId, status: "pending" });
}
async function handleStatus(req, res) {
  const profileCtx = await authenticateExportRequest(req);
  const jobId = req.query.jobId;
  if (!jobId || typeof jobId !== "string") {
    return res.status(400).json({ error: "Missing jobId" });
  }
  const adminDb = getAdminDb();
  const result = await adminDb.query({
    exportJobs: { $: { where: { id: jobId } } }
  });
  const job = result.exportJobs?.[0];
  if (!job) return res.status(404).json({ error: "Job not found" });
  if (job.requesterUserId !== profileCtx.userId) {
    return res.status(403).json({ error: "Forbidden" });
  }
  return res.status(200).json({
    jobId: job.id,
    status: job.status,
    downloadUrl: job.downloadUrl || null,
    rowCount: job.rowCount ?? 0,
    truncated: job.truncated ?? false,
    warningHeader: job.warningHeader ?? "",
    errorMessage: job.errorMessage ?? "",
    format: job.format,
    exportType: job.exportType
  });
}
async function handleAck(req, res) {
  const profileCtx = await authenticateExportRequest(req);
  const body = parseBody(req.body) ?? {};
  const jobId = body.jobId;
  if (!jobId) return res.status(400).json({ error: "Missing jobId" });
  const adminDb = getAdminDb();
  const result = await adminDb.query({
    exportJobs: { $: { where: { id: jobId } } }
  });
  const job = result.exportJobs?.[0];
  if (!job) return res.status(404).json({ error: "Job not found" });
  if (job.requesterUserId !== profileCtx.userId) {
    return res.status(403).json({ error: "Forbidden" });
  }
  await logExportDownloaded(jobId);
  return res.status(200).json({ ok: true });
}
async function handleProcess(req, res) {
  if (!verifyCronSecret(req)) {
    return res.status(401).json({ error: "Unauthorized" });
  }
  const jobId = req.query.jobId;
  if (jobId && typeof jobId === "string") {
    const job = await processExportJob(jobId);
    return res.status(200).json({ processed: 1, outcomes: [{ jobId, status: job?.status }] });
  }
  const outcomes = await processPendingJobs(5);
  return res.status(200).json({ processed: outcomes.length, outcomes });
}
async function handler(req, res) {
  const actionFromQuery = typeof req.query.action === "string" ? req.query.action : "";
  const isCronGet = req.method === "GET" && verifyCronSecret(req) && !req.query.jobId && (!actionFromQuery || actionFromQuery === "process");
  const action = actionFromQuery || (isCronGet ? "process" : req.method === "GET" ? "status" : "create");
  try {
    if (action === "create" && req.method === "POST") {
      return await handleCreate(req, res);
    }
    if (action === "status" && req.method === "GET") {
      return await handleStatus(req, res);
    }
    if (action === "ack" && req.method === "POST") {
      return await handleAck(req, res);
    }
    if (action === "process" && (req.method === "POST" || req.method === "GET")) {
      return await handleProcess(req, res);
    }
    return res.status(405).json({ error: "Method not allowed" });
  } catch (e) {
    console.error("[export]", e);
    const status = e.status ?? 500;
    return res.status(status).json({
      error: e instanceof Error ? e.message : "Export request failed"
    });
  }
}
module.exports = module.exports.default || module.exports;
